In [1]:
import pandas as pd
import os
import shutil
import json

Creating the directory structure to save Output for Images

In [2]:
output_data_path = os.path.join("output")
os.makedirs(output_data_path, exist_ok=True)
output_data_images_path = os.path.join("output", "images")
os.makedirs(output_data_images_path, exist_ok=True)

Reading the data

In [3]:
vqa_data = pd.read_csv('../data/path_open_vqa.csv')
vqa_data = vqa_data.rename(columns={vqa_data.columns[2]: 'Image1_Path',
                                    vqa_data.columns[26]: 'Image2_Path',
                                    vqa_data.columns[27]: 'Image3_Path',
                                    vqa_data.columns[28]: 'Image4_Path',
                                    vqa_data.columns[29]: 'Image5_Path',
                                    'Image 1 Magnification ': 'Image1_Mag',
                                    'Image 2 Magnification ': 'Image2_Mag',
                                    'Image 3 Magnification ': 'Image3_Mag',
                                    'Image 4 Magnification ': 'Image4_Mag',
                                    'Image 5 Magnification ': 'Image5_Mag'})

# Converting all the NaN values to None values to mark the missing values rather than being read as 'nan'
vqa_data = vqa_data.astype(object).where(pd.notnull(vqa_data), None)
vqa_data = vqa_data.reset_index()
vqa_data['index'] = vqa_data['index'] + 1
vqa_data = vqa_data.rename(columns={'index': 'Case_ID'})
vqa_data.head()

,Case_ID,Timestamp,Pathologist ID,Image1_Path,Organ,Categorization,Regional Anatomy,Open Ended - Question 1,Open Ended - Answer 1,Open Ended - Answer 2,...,Open Ended - Wrong Answer 1,Open Ended - Wrong Answer 2,Image2_Mag,Image3_Mag,Image4_Mag,Image5_Mag,Image2_Path,Image3_Path,Image4_Path,Image5_Path
0,1,2/25/2025 13:41:20,CK,https://drive.google.com/open?id=1tgv50Q9W4Bm_...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the primary architectural pattern obse...,Nodular pattern,Germinal centers are absent,...,None,None,None,None,None,None,None,None,None,None
1,2,2/25/2025 13:46:25,CK,https://drive.google.com/open?id=1igYpj4RL0XKx...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the predominant cell type seen here?,The main cell type observed here is a lymphocy...,These would best be characterized as small lym...,...,None,None,None,None,None,None,None,None,None,None
2,3,2/25/2025 13:51:37,CK,https://drive.google.com/open?id=1DKNZJQJ17SkX...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,"In this mantle cell lymphoma, what is the best...",The nuclei of the abnormal lymphocytes are mos...,This should be considered a highly cellular ti...,...,None,None,None,None,None,None,None,None,None,None
3,4,2/26/2025 11:30:23,CK,https://drive.google.com/open?id=1jUe0z6wlZ0s9...,Gastrointestinal - Small Intenstine,Infection (Benign),Intestinal villous mucosa,"In a child with poor weight gain, what are the...",Features that argue against celiac disease in ...,Granulomas here are often the consequence of u...,...,None,None,None,None,None,None,None,None,None,None
4,5,2/26/2025 11:42:26,CK,https://drive.google.com/open?id=1VNr78I5w671g...,Gastrointestinal - Dudenum,Infection (Benign),Intestinal villous mucosa,What are the main histologic features of a non...,Non-necrotizing granulomas are characterized b...,None,...,None,None,None,None,None,None,None,None,None,None

#### Image Magnification Issue

It was reported that the Pathologist CK didn't include the magnification of the eyepience lens (10x) while reporting the resolution of the images where pathologist AC included all those. So, to make this data consistent, resolutions collected by CK are being multiplied with 10 to ensure that resolution reflects the objective magnification of the microscope multiplied by the eyepiece lens magnification

Image Magnifications Reported by AC

In [4]:
vqa_data[vqa_data['Pathologist ID'] == 'AC'][['Image1_Mag', 'Image2_Mag', 'Image3_Mag']].apply(pd.Series.value_counts)

      Image1_Mag  Image2_Mag  Image3_Mag
100x          23         NaN         NaN
200x          19         NaN         NaN
20x            2         NaN         NaN
400x           4         NaN         NaN
40x            4         NaN         NaN

Image Magnifications Reported by CK

In [5]:
vqa_data[vqa_data['Pathologist ID'] == 'CK'][['Image1_Mag', 'Image2_Mag', 'Image3_Mag']].apply(pd.Series.value_counts)

     Image1_Mag  Image2_Mag  Image3_Mag
10X         1.0         NaN         NaN
10x        31.0         6.0        10.0
20x        33.0        11.0        10.0
2x         13.0         7.0         2.0
40x         8.0         3.0         2.0
4X          NaN         NaN         1.0
4x         16.0        10.0         8.0
5X          1.0         NaN         NaN
5x          2.0         NaN         4.0

This shows that CK did not incorporate the magnification of eyepiece lens (10x) when reporting the overall image resolution. So multiplying all the magnifications reported by CK by 10 will make our data consistent

In [6]:
def convert_mag(mag):
    path_id = mag.iloc[0]
    image_mag = mag.iloc[1]
    if pd.isnull(image_mag):
        return image_mag
    
    image_mag = image_mag.lower().strip()
    if path_id == 'CK':    
        if 'x' in image_mag:
            return str(int(image_mag.split('x')[0]) * 10) + 'x'
    return image_mag

In [7]:
vqa_data['Image1_Mag'] = vqa_data[['Pathologist ID', 'Image1_Mag']].apply(convert_mag, axis=1)
vqa_data['Image2_Mag'] = vqa_data[['Pathologist ID', 'Image2_Mag']].apply(convert_mag, axis=1)
vqa_data['Image3_Mag'] = vqa_data[['Pathologist ID', 'Image3_Mag']].apply(convert_mag, axis=1)
vqa_data.head()

,Case_ID,Timestamp,Pathologist ID,Image1_Path,Organ,Categorization,Regional Anatomy,Open Ended - Question 1,Open Ended - Answer 1,Open Ended - Answer 2,...,Open Ended - Wrong Answer 1,Open Ended - Wrong Answer 2,Image2_Mag,Image3_Mag,Image4_Mag,Image5_Mag,Image2_Path,Image3_Path,Image4_Path,Image5_Path
0,1,2/25/2025 13:41:20,CK,https://drive.google.com/open?id=1tgv50Q9W4Bm_...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the primary architectural pattern obse...,Nodular pattern,Germinal centers are absent,...,None,None,None,None,None,None,None,None,None,None
1,2,2/25/2025 13:46:25,CK,https://drive.google.com/open?id=1igYpj4RL0XKx...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the predominant cell type seen here?,The main cell type observed here is a lymphocy...,These would best be characterized as small lym...,...,None,None,None,None,None,None,None,None,None,None
2,3,2/25/2025 13:51:37,CK,https://drive.google.com/open?id=1DKNZJQJ17SkX...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,"In this mantle cell lymphoma, what is the best...",The nuclei of the abnormal lymphocytes are mos...,This should be considered a highly cellular ti...,...,None,None,None,None,None,None,None,None,None,None
3,4,2/26/2025 11:30:23,CK,https://drive.google.com/open?id=1jUe0z6wlZ0s9...,Gastrointestinal - Small Intenstine,Infection (Benign),Intestinal villous mucosa,"In a child with poor weight gain, what are the...",Features that argue against celiac disease in ...,Granulomas here are often the consequence of u...,...,None,None,None,None,None,None,None,None,None,None
4,5,2/26/2025 11:42:26,CK,https://drive.google.com/open?id=1VNr78I5w671g...,Gastrointestinal - Dudenum,Infection (Benign),Intestinal villous mucosa,What are the main histologic features of a non...,Non-necrotizing granulomas are characterized b...,None,...,None,None,None,None,None,None,None,None,None,None

### Generating the Google Sheet Containing the mapping between Google Drive Links and Image Names

This will help to map the image names downloaded from collected data with the Google Drive Links we have in our data

In [8]:
# function listFilesInNestedFolders(parentFolderId) {
#   // Get the initial parent folder
#   var parentfolder_id = '1VdFeRx06PrTTCbeMVQ0wQ8ML8QF8sSxM-QWlTcMx7TKQAjpWRuW5-EWJi-DtuBDPeXTbGYNm'
#   const parentFolder = DriveApp.getFolderById(parentfolder_id);
#   var folderlisting = 'File Names and Links - '+ parentfolder_id;

#   var ss = SpreadsheetApp.create(folderlisting);
#   var sheet = ss.getActiveSheet();
#   sheet.appendRow(['name','link']);

#   // Get subfolders in the current folder and process them recursively
#   var subfolders = parentFolder.getFolders();
#   while (subfolders.hasNext()) {
#     var subfolder = subfolders.next();
#     // Get files in the current folder
#     var contents = subfolder.getFiles();
#     var file;
#     var name;
#     var link;
#     while (contents.hasNext()) {
#       file = contents.next();
#       name = file.getName();
#       link = file.getUrl();
#       sheet.appendRow([name,link]);
#     }
#   }
# }

Now Download the file generated which contains mapping between google drive links and names.

In [9]:
data_dir = "../data_eval"
file_name = "file_names_and_links_PathOpen_Images.csv"
file_path = os.path.join(data_dir, file_name)
google_drive_name_links = pd.read_csv(file_path)
google_drive_name_links['google_drive_image_id'] = google_drive_name_links['link'].apply(lambda x: x.split('/')[-1])
google_drive_name_links.head()

,name,link,google_drive_image_id
0,ck_HSP_5x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/1SYbssi84BMfkC...,1SYbssi84BMfkCcUAHSYiDOl7JSgTVKe1
1,ck_BALL_4x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/1XrSu7uRm3s-al...,1XrSu7uRm3s-alWtSOdgieuS2f2L2bnDd
2,ck_pschwannoma_20x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/1dGZ8MAgdKvT5w...,1dGZ8MAgdKvT5wd81FU8lMeXaVPJYMj_s
3,ck_CMV gastritis_4x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/11UMXpBZjiQdo0...,11UMXpBZjiQdo0cnHVeR_-rdISv_aMlnO
4,ck_rhabdo_5x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/174myggtY1Fj5A...,174myggtY1Fj5Av5gFJmOnC9XZohKcN-e

Creating dict between Google Drive Image and Name

In [10]:
imageid_name_dict = dict(zip(google_drive_name_links['google_drive_image_id'], google_drive_name_links['name']))
imageid_name_dict

{'1SYbssi84BMfkCcUAHSYiDOl7JSgTVKe1': 'ck_HSP_5x - Chandra Krishnan.jpeg',
 '1XrSu7uRm3s-alWtSOdgieuS2f2L2bnDd': 'ck_BALL_4x - Chandra Krishnan.jpeg',
 '1dGZ8MAgdKvT5wd81FU8lMeXaVPJYMj_s': 'ck_pschwannoma_20x - Chandra Krishnan.jpeg',
 '11UMXpBZjiQdo0cnHVeR_-rdISv_aMlnO': 'ck_CMV gastritis_4x - Chandra Krishnan.jpeg',
 '174myggtY1Fj5Av5gFJmOnC9XZohKcN-e': 'ck_rhabdo_5x - Chandra Krishnan.jpeg',
 '1DGvPSPr7z63T7ly9QrlqwvQMY_sx4at3': 'ck_dura chl_10x - Chandra Krishnan.jpg',
 '19KsfXwd-HtN_ZOtYq3qzPcdKC9GxMUnR': 'ck_arpckd_10x - Chandra Krishnan.jpg',
 '1m3sG-JnULD4PxMWvZ8_eCk7IUxvGDwjB': 'ck_candida esophagitis_10x - Chandra Krishnan.jpg',
 '1XNAKCVMmz6oBbIRN0DKNXK9EbzhVkiZ1': 'ck_corpus luteum_4x - Chandra Krishnan.jpg',
 '1mIsQXUpuUFe5e5q8nW5f7sXpXCj3N95g': 'ck_lch_4x - Chandra Krishnan.jpeg',
 '1v0CWoU4lmdth83vf6JoCu62J0-IsVF_x': 'ck_midlineg_20x - Chandra Krishnan.jpeg',
 '13LyGLMR7gjLf75nZHOzP_iS1simU2Dxd': 'ck_breast lactation_4x - Chandra Krishnan.jpeg',
 '1rJeENEFUzryNuJefmzY_TAC6QqDxlzPK': 'ck_met yst_4x - Chandra Krishnan.jpeg',
 '17oUrl4V-rlQ3B6daa2yyvZXBY0I3WEG0': 'ck_angiosarc_4x - Chandra Krishnan.jpeg',
 '1LUzmvgCfrSjGO_SKPBxSB1SHptX0Oq8Q': 'ck_panc NET_2x - Chandra Krishnan.jpeg',
 '19aTtWgO8egBG9oMcijOaFXrfM14_Kxeh': 'ck_graves_20x - Chandra Krishnan.jpeg',
 '10Z6tLd4wKNSnuOYXlqZGeo-yv60Slk2R': 'ck_okc_20x - Chandra Krishnan.jpeg',
 '1y1R3GgbTUOe1hxfFeJE4ylVks2tmFRoy': 'ck_molluscum_10x - Chandra Krishnan.jpg',
 '1NEkqd0p5AqK4MeNYd_-qqE3iLuqrMnVI': 'ck_mucinous adeno_20x - Chandra Krishnan.jpeg',
 '1xo0jMw_41qVpOOmiiLdXosdm_tZiywZd': 'ck_pheo_10x - Chandra Krishnan.jpeg',
 '1tWQ8FH1UEg1U2GJD-Z-xAgHe98cK66Rx': 'ck_CHM_20x - Chandra Krishnan.jpeg',
 '1xQrRxN-UafIdnKf6578PDWoDIoFz3TKC': 'ck_tonsil scc_40x - Chandra Krishnan.jpeg',
 '1wnDx5PQahOA43aDYLOQbr2PSdqARlYnv': 'ck_granularct_4x - Chandra Krishnan.jpeg',
 '1OCcjbI9WN0o5P8dss4SfP0GlMJ-XsVbD': 'ck_liverhepc_2x - Chandra Krishnan.jpeg',
 '1yeLEOAo_OoeVo3Np7cFp0x7pBh8s13ME': 'ck_fnh_20x - Chandra Krishnan.jpeg',
 '1HL6xUTmNzOHV75_j5Nu8MUWh8rDi6xt5': 'ck_mycobacterial infection_10x - Chandra Krishnan.jpg',
 '1auUUk_01rJRMktA4lGQx6HLFBkOcuB8H': 'ck_trichofolliculoma_10x - Chandra Krishnan.jpg',
 '1nIdXvoZrRTaYc5Cmf3ssJnfD9Ljkc2ve': 'ck_fibrous obliteration_10x - Chandra Krishnan.jpg',
 '1kZ-xxiZPbsmvBZ8O9JKBZeiAHaQKtsBg': 'ck_cellular fibroadenoma_4x - Chandra Krishnan.jpg',
 '1rhQTDQ3t116yKfNXE9QK_m6jU2X0VzCR': 'ck_keloid_5x - Chandra Krishnan.jpg',
 '1Ap7zdKbExdkhRtnrhM0ycNsJhqBySXyV': 'ck_avm_10x - Chandra Krishnan.jpg',
 '1_CLKlfOLl4oKIkiZANpP32a0FhHZ_vVF': 'ck_endometrioid figo1_10x - Chandra Krishnan.jpeg',
 '1WNxXNJV5krnGIq24AiU0378W_qgJqj6Z': 'ck_clear cell carcinoma_20x - Chandra Krishnan.jpeg',
 '1FpuA_u8Ws2GbLjxES73QHcRvqJY4PGoE': 'ck_invasive lobular_5x - Chandra Krishnan.jpeg',
 '1xYOpGM7-iyXRh2AHVm9PPhLYrqhi4rgr': 'ck_fibroadenoma_20x - Chandra Krishnan.jpeg',
 '1PDfH701aJbgAYkkFAuBl1LLBHArZJOhB': 'ck_yolk sac tumor_40x - Chandra Krishnan.jpg',
 '1I-wbytP5TqHkvU-wvnCxaPBS19hZxkNg': 'ck_branchial arch_20x - Chandra Krishnan.jpg',
 '1VG68PKvwKQCBqGoR-QnZjjf7WpaZm9tk': 'ck_HSP_10x - Chandra Krishnan.jpeg',
 '1JZr0pAu8eC94-Kt5qTa4Io_llgfVZ2un': 'ck_BALL_20x - Chandra Krishnan.jpeg',
 '1_NEuM0kGIKLeMpAd1eyAivjMkS16ayH_': 'ck_pschwannoma_4x - Chandra Krishnan.jpeg',
 '1_pVsVzF4mmeE7wRyoF2-FVgR1SknXO5k': 'ck_CMV gastritis_20x - Chandra Krishnan.jpeg',
 '1FWrc_FrPDCt_qkapb6hwDPbBLIxCpbC-': 'ck_rhabdo_10x - Chandra Krishnan.jpeg',
 '10tTIf4L7WDoEuh4CTIIFepJe1acCLILM': 'ck_dura chl_40x - Chandra Krishnan.jpg',
 '1x33SWoWd0_Kj7xw-Lp8e86B6-SnavvUq': 'ck_arpckd_2x - Chandra Krishnan.jpg',
 '1dzDcnZQiw60HTcNWLNgXYe3P3H8jhB2Z': 'ck_candida esophagitis_40x - Chandra Krishnan.jpg',
 '1Nl7Doml8aD_Oj4TUWMyXZ9rx_lX5aev-': 'ck_corpus luteum_20x - Chandra Krishnan.jpg',
 '1ln88YYdKeCOQGbph4yM5grPHRdZin4vU': 'ck_lch_10x - Chandra Krishnan.jpeg',
 '163YaXt8dRDNI9IziCKRfcvnTGzX4tB2b': 'ck_midlineg_4x - Chandra Krishnan.jpeg',
 '12oRrn3NtZQps_N4SDiwDnx-klquXCH_W': 'ck_breast lactation_20x - Chandra Krishnan.jpeg',
 '12xPORhKOHlYP8YD06fbgJfnumUIb-G53': 'ck_met yst_20x - Chandra Krishnan.jpeg',
 '19JC1JY8CQTDg7oAlaqrDxGPc8YqLoB8i': 'ck_angiosarc_10x - Chandra Krishnan.jpeg',
 '1-j_6Wx4iaghDtjwkIqQck7HXPVn6Hiox': 'ck_panc NET_20x - Chandra Krishnan.jpeg',
 '1cBf6gSp6SZkb_m1cg7Jtlwm2KrU1rG6s': 'ck_graves_4x - Chandra Krishnan.jpeg',
 '1406KBZBltBvboJbvaCv7b1jQQvbi0-mQ': 'ck_okc_2x - Chandra Krishnan.jpeg',
 '1eqQP5hGq9U2iS8b5KIWhx8MH0nx9yBsv': 'ck_molluscum_20x - Chandra Krishnan.jpg',
 '1cZ1Pf-d9E3uNWm3My92w2XYk1fjNDCMi': 'ck_mucinous adeno_4x - Chandra Krishnan.jpeg',
 '1c8Ze_6T38iNfY710aT0hM4Bn1VQwSdvI': 'ck_pheo_2x - Chandra Krishnan.jpeg',
 '1B6TXzOFuXHljUUkUmet12L25n-hPVkXp': 'ck_CHM_4x - Chandra Krishnan.jpeg',
 '1DvJdSRUhM99KTqftJ9NNf8hBIcfxtrhH': 'ck_tonsil scc_4x - Chandra Krishnan.jpeg',
 '1lCOIor0N1M9RveOuzbS5ujWNaAw5Cthd': 'ck_granularct_20x - Chandra Krishnan.jpeg',
 '1WKyBU-xI0MxS2MvM5rlvIMCAY6jlu87T': 'ck_liverhepc_20x - Chandra Krishnan.jpeg',
 '1xdfD4BWK1y8WsHtx25UA-azcjl5e62-2': 'ck_fnh_2x - Chandra Krishnan.jpeg',
 '1_XLVxpxM4IYza9-Sj2Rn1rMZeen4dJJS': 'ck_mycobacterial infection_2x - Chandra Krishnan.jpg',
 '1BWInTWBb9BTpwwzxnDYyGQXaKry4TlcF': 'ck_trichofolliculoma_4x - Chandra Krishnan.jpg',
 '1_BqvwrDIGZsCSRhlsn-OAqbbtY0O7aY2': 'ck_fibrous obliteration_4x - Chandra Krishnan.jpg',
 '1uw2hmn23nxEQF8Mtjv62EnryI23VAiSv': 'ck_cellular fibroadenoma_20x - Chandra Krishnan.jpg',
 '1GL0Flv76LqPlRybjWnxRhYtONiNgKW0X': 'ck_keloid_40x - Chandra Krishnan.jpg',
 '1W-6cFEIERzFo2vgI5OkhryZ15HIR9RZk': 'ck_avm_2x - Chandra Krishnan.jpg',
 '1gva2VDtX52gD3MCv0AXxZpzEty3bOVgv': 'ck_endometrioid figo1_4x - Chandra Krishnan.jpeg',
 '1iq4heBQ-Vx0okmWh4AjDBGTJmQuKpyoa': 'ck_clear cell carcinoma_2x - Chandra Krishnan.jpeg',
 '1mmbk-srX_j-fGcSa8UxnSl8BX2ZGESdF': 'ck_invasive lobular_10x - Chandra Krishnan.jpeg',
 '1RTTNNtnUUj1NgxLJcHidN45-L__BQL68': 'ck_fibroadenoma_10x - Chandra Krishnan.jpeg',
 '1MGVUcPqG_YUQmk6VnZ4h5WEGCHfzmrda': 'ck_yolk sac tumor_20x - Chandra Krishnan.jpg',
 '1Fhg0ERGYAQKdNR5y1t3u_dCoTZjX9PXa': 'ck_branchial arch_4x - Chandra Krishnan.jpg',
 '1L-hUnZ7Z4Hte8A6MvGg-KRxeNhRdW4mS': 'ck_HSP_20x - Chandra Krishnan.jpeg',
 '1MXE7pIGVTBFU2D66LHBomaXg3TN-inwK': 'ck_BALL_10x - Chandra Krishnan.jpeg',
 '1FiSAz-uYKtF8a3rym8VjlvtMHEZmOWve': 'ck_pschwannoma_10x - Chandra Krishnan.jpeg',
 '1mckAkMR3feYdpzMtdyDGfgUmGBKyZ5Yf': 'ck_CMV gastritis_10x - Chandra Krishnan.jpeg',
 '1WrGDIP6b4Xw_m946Y1_cKDKZcsq-Fr1s': 'ck_rhabdo_20x - Chandra Krishnan.jpeg',
 '1kkxCwjIZfZI8s6RZY4l8s18gIe1-1dJc': 'ck_dura chl_20x - Chandra Krishnan.jpg',
 '1zRaWaadmqbCre0k6fd4HWc1l2_1XTC4g': 'ck_arpckd_4x - Chandra Krishnan.jpg',
 '1wqtJcmkUrF2pKxjWotpVK5Mlgi516hzN': 'ck_candida esophagitis_20x - Chandra Krishnan.jpg',
 '19Hcl1Nre0edkxfjTyjB_n7C8J3CclCAY': 'ck_corpus luteum_10x - Chandra Krishnan.jpg',
 '1SNa7Z__lfmCRxOo5GGTzLdlxBOa7vIB7': 'ck_lch_20x - Chandra Krishnan.jpeg',
 '10nEyPnldx5MebOGLfERit3wSaxmxd0cK': 'ck_midlineg_10x - Chandra Krishnan.jpeg',
 '1nkhjZMXsY1C2L90Nrn6kXDq_gZRf0f5u': 'ck_breast lactation_10x - Chandra Krishnan.jpeg',
 '1SIoqmAkVVS2NBwxlqQd3Zt8GTrJUz6Jh': 'ck_met yst_10x - Chandra Krishnan.jpeg',
 '1cDoUoMP0L2lP953K-1Cftjd4sjvlpODR': 'ck_angiosarc_20x - Chandra Krishnan.jpeg',
 '19CKM1AEPiXp4Y-rUaRLzgEeMuHAFo8SS': 'ck_panc NET_4x - Chandra Krishnan.jpeg',
 '1y6lc1Udb58wCITJexy8SMQQCOZK4RHs5': 'ck_graves_10x - Chandra Krishnan.jpeg',
 '13TeCua-zmI6HIfKF0u7aYzeF9MFHjP72': 'ck_okc_4x - Chandra Krishnan.jpeg',
 '1kDb8-wrmpFbLWv8lpNXu5xLSkRm97xSv': 'ck_molluscum_40x - Chandra Krishnan.jpg',
 '12ZNvhbi81S1C8g3Pi9arrJ2eW6ukeWbW': 'ck_mucinous adeno_10x - Chandra Krishnan.jpeg',
 '14WeEzKwrntHzlYfGj97U0iSGu8UvzBaz': 'ck_pheo_4x - Chandra Krishnan.jpeg',
 '1VxfxsY0SYG9PZ9F4JfLpn5x5I4I5bM-D': 'ck_CHM_10x - Chandra Krishnan.jpeg',
 '1Jjg5iv9NXZrTc7cS91FidWzQnvrK_3sn': 'ck_tonsil scc_10x - Chandra Krishnan.jpeg',
 '1vpO5NSkfeqFJvoCgiQk8H3OU3BZI6qhk': 'ck_granularct_10x - Chandra Krishnan.jpeg',
 '1lpUqfcAHA2l47izD71N6MHBep9c_Mt9W': 'ck_liverhepc_10x - Chandra Krishnan.jpeg',
 '1oPZs20zogm4svXyMGYHS0G1A_vR8UtAa': 'ck_fnh_5x - Chandra Krishnan.jpeg',
 '1v6S_LTC0E2UaZo4M62XvVLfoEqQ9Vimt': 'ck_mycobacterial infection_4x - Chandra Krishnan.jpg',
 '1nUip_rlZEaIMVD5oXcG8ca7fFbKEvGDW': 'ck_trichofolliculoma_2x - Chandra Krishnan.jpg',
 '1BSua6upeA1LD2b8FBtuPGxaZEugMENka': 'ck_fibrous obliteration_2x - Chandra Krishnan.jpg',
 '1Abv0fJQzO2bRniWMSS3ao5b4NsdKlSpI': 'ck_cellular fibroadenoma_10x - Chandra Krishnan.jpg',
 '1tOkOS2wvn03BwrMJBnObOxe6vakWqgx4': 'ck_keloid_20x - Chandra Krishnan.jpg',
 '1XYu5JPENCl7fAwvqDNGontyjYdZLroHO': 'ck_avm_4x - Chandra Krishnan.jpg',
 '1ZeBueBr51LvUqRCXUD8cc1L7Q75mIDh9': 'ck_endometrioid figo1_2x - Chandra Krishnan.jpeg',
 '1LHafvP12xqXr09y8m9gb99utMT0SlTej': 'ck_clear cell carcinoma_10x - Chandra Krishnan.jpeg',
 '1Q7sEAaVC8tEJoqSJE3QfWcb4nXKrwaad': 'ck_invasive lobular_20x - Chandra Krishnan.jpeg',
 '1H72ZqDMvo4SL7-eEfcjQpP2E_L2OdPgp': 'ck_fibroadenoma_2x - Chandra Krishnan.jpeg',
 '1QZTpVFxZNzidyy1agUX-m2Ma-fNPr1pu': 'ck_yolk sac tumor_10x - Chandra Krishnan.jpg',
 '1eVF-T5Ie2wY2YIIaAspvTSGHmZ-7_vOs': 'ck_branchial arch_2x - Chandra Krishnan.jpg',
 '13118rBmyVKdO46amnks6-9yQViYRp1qV': 'ck_bowel lymphoma_20x - Chandra Krishnan.jpg',
 '1k885zCGHZIA3BygDTvZ9Lyb_-ahm1VFo': 'ck_herniasac_4x - Chandra Krishnan.jpg',
 '1enSQJ6jDucV1zW-ys2RoUyn59b3RMpmq': 'ck_stomach body_40x - Chandra Krishnan.jpg',
 '1-rmYiJzbA24Rzi_REBsAeh6rKkVpSnOd': 'ck_wilms tumor_20x - Chandra Krishnan.jpeg',
 '1F1HQgvUapA3vEuaJmmFqBs1Wq1_qGpUh': 'ck_marrow AML_20x - Chandra Krishnan.jpg',
 '1YEFJSmR82RYqu1OUM5wfxiPNaHlAIV8D': 'ck_marrow aplasia_4x - Chandra Krishnan.jpg',
 '1s3h1WgEKM_KKQo5gfcp9isLT_DcBhyoe': 'ck_osteoblastoma_20x - Chandra Krishnan.jpg',
 '1L0uPKvAa0CmX8Ckagv5JWgOt4wAdCpi-': 'ck_plasmacytoma_amyloid_20x - Chandra Krishnan.jpg',
 '1YH_FZ2gRZa305QDNWWKBnSB3GNLZ2H0Y': 'ck_melanoma ulcer_20x - Chandra Krishnan.jpeg',
 '1qQylVYAELk111DyA5xbkn_v89md9cDOr': 'ck_ganglion cyst_20x - Chandra Krishnan.jpeg',
 '1h7k23l4G2czQJ6W38nTTQT2C62c8DhdR': 'ck_parathyroid adenoma_4x - Chandra Krishnan.jpeg',
 '1nFYBpX-mtTLrbTUZscfDPu5s8KxXVlxl': 'ac_img51_40x - Amy Coffey.jpeg',
 '1v0-WTGvwL1hk-1hWqLQs4mhJXXnnaAB3': 'ac_img50_100x - Amy Coffey.jpeg',
 '12QsvEK1Yy-9tS7MxpVFKTaiAfBU2ymlV': 'ck_thrombus fibrin_20x - Chandra Krishnan.jpg',
 '1LtoxQb4jWLxOwarS5c0u44ceOhtY0Ilh': 'ck_osteochondroma_4x - Chandra Krishnan.jpg',
 '1vdoImxFJp5GPl2c3PSf8cdIQ7XG_VrR1': 'ck_acute osteomyelitis_20x - Chandra Krishnan.jpg',
 '1iz0IgbgqzCcJNgsEe55H1J36mbjjtOmy': 'ac_img49_100x - Amy Coffey.jpeg',
 '1K4XcYs2u_3qq863v0o4gk8tOlNCgwCDv': 'ac_img48_40x - Amy Coffey.jpeg',
 '1sEzOOJykYqP0funlt1MvGoFnMhZ7b3P6': 'ac_img47_200x - Amy Coffey.jpeg',
 '1_aeqYaOyzcp66O30ouaSOJLSfgRXO4p-': 'ac_img46_100x - Amy Coffey.jpeg',
 '19BCokgiMELG10o4zbbmt2aguGGuESuU9': 'ac_img45_100x - Amy Coffey.jpeg',
 '16FntYOr7bqU5lMm_HmcvteV3v6mCn_xF': 'ac_img44_200x - Amy Coffey.jpeg',
 '1DEEw5vjjecbromHvfMyWq0SomIhDk2Xs': 'ac_img43_200x - Amy Coffey.jpeg',
 '1h_niAtvlq6QSqDqwaBiGLiyesETgUm8g': 'ck_placental infarct_5x - Chandra Krishnan.jpeg',
 '1o3UGD4YoSFxvJFhUF0ul-0b3SYygdbSn': 'ac_img42_20x - Amy Coffey.jpeg',
 '1FVmt8pVU3GSATpqXCvbIbnp3S-IhKmz1': 'ac_img25_400x - Amy Coffey.jpg',
 '1HSA9XjTRwfkD4qfXLZB6cZsqTZZ_AS7b': 'ac_img40_100x - Amy Coffey.jpg',
 '1KAa3yrSyeUE4Py_mFmDBQ89rr6iHo2ni': 'ac_img39_100x - Amy Coffey.jpg',
 '1p5JHByFaorTdI9tle1FBFS408mJTShE0': 'ac_img38_100x - Amy Coffey.jpg',
 '1wb6pvxaDoACixh2otwWLN0B1G1XEHzUY': 'ac_img37_200x - Amy Coffey.jpg',
 '16EtYPfQr8_D_4kH8wXBY_nuRiwNw_dXc': 'ac_img36_100x - Amy Coffey.jpg',
 '1qY2L0pP3T6q0H-pUcuzdsX-J0r3o0Yzm': 'ac_img35_100x - Amy Coffey.jpeg',
 '1iUrB0NN_MVlcG7oggz8tRvG9a1yC5GLv': 'ac_img34_100x - Amy Coffey.jpeg',
 '11O1XdAFAB9TGah2YC_WurxSzt7tlemHy': 'ac_img33_100x - Amy Coffey.jpeg',
 '1TGqodZmT6Dtj20jJBILdXrxcFeL27d8b': 'ac_img32_200x - Amy Coffey.jpeg',
 '1Yhc6gh8ZPUZjS2SDGawvA3nGxzqbpb5d': 'ac_img31_100x - Amy Coffey.jpeg',
 '1qiefvCxR8YKDfqkg0X2ANI_1ekwbIrZE': 'ac_img30_200x - Amy Coffey.jpeg',
 '1krz-xRoyoqrX5LcPoZRCaQzYBUvXVnsv': 'ac_img29_100x - Amy Coffey.jpeg',
 '1REXrDteXd7va6X_dM6sGa3Sg7yfdj2CP': 'ck_dermatofibroma_4x - Chandra Krishnan.jpg',
 '1FmugbtkmH4Fg2rVk8WKw_RgwSZhmJUVe': 'ck_torsion_10x - Chandra Krishnan.jpg',
 '1q7SFWU1zbhuHO3RYrW5Y7PV_spPUX05c': 'ck_placenta membrane_20x - Chandra Krishnan.jpeg',
 '1avNYoJeBGrCXh4w2ViCxRtcsWuIveb8S': 'ck_dermatofibroma_4x - Chandra Krishnan.jpg',
 '1SWy9uYqr5_Y5S-4JVxLZsfsbw89T6qfE': 'ac_img28_100x - Amy Coffey.jpg',
 '15NOn1ZIrCURdrOqvhgnIvKgLyqq1Kb18': 'ac_img27_200x - Amy Coffey.jpeg',
 '1NFK0iG0ARqfpCvJnMxjTPum7h6QeuB5N': 'ac_img26_100x - Amy Coffey.jpeg',
 '1n9QDIwHTADQ7NeKzD7HuPaNDuSDP54sh': 'ac_img25_200x - Amy Coffey.jpeg',
 '1W0G0fov6MkKNutdbHq3rOnRn-gBftpD-': 'ac_img24_100x - Amy Coffey.jpeg',
 '1x4N-Lf-g6TbyShzxjVJ-JeO0SdbFjTyX': 'ac_img23_100x - Amy Coffey.jpeg',
 '17FQY8_cJC8tXJuG9fgkPW14PFZxEdBnS': 'ac_img22_100x - Amy Coffey.jpeg',
 '1ibFWmslUJ0wqv70tyRnGix9uLwBOgg_g': 'ck_aneurysmal bone cyst_10x - Chandra Krishnan.jpg',
 '1oIAu4puQJaJ-Lq94lbIadtMzDvvrASR_': 'ac_img21_200x - Amy Coffey.jpeg',
 '1Dml_-g8JOP4Y3j5uRhPOHmSz23A0QGhM': 'ac_img20_200x - Amy Coffey.jpeg',
 '1_beSmXXPq4sVmHxxvKpUax7YFzI9wW9G': 'ac_img19_200x - Amy Coffey.jpeg',
 '1iNpg3DgTGpNZdHToSpzyOdxHAObAdkZA': 'ac_img18_100x - Amy Coffey.jpeg',
 '1sT4gNeuYMV3RepkLeGZBd3vr1dkffxqh': 'ac_img17_20x - Amy Coffey.jpeg',
 '1j8_coGLWD4C9ZpIerR6NYmYZEkbgVw0Y': 'ac_img16_200x - Amy Coffey.jpeg',
 '1qiBYBEmm9TXiPjyAC43hM1TBMe6Da393': 'ac_img15_200x - Amy Coffey.jpg',
 '1oenGyiwnXtCJ71_IcY5TMqK2f6jRGyRP': 'ck_eosinophilic esophagitis_40x - Chandra Krishnan.jpg',
 '1iisbShaoX0qk1QTqrKVTBd0qYr2BbQKe': 'ck_invasive melanoma_20x - Chandra Krishnan.jpeg',
 '1UCxGrtxEXsU0ym68rOFZvcUa7BKXBbSm': 'ck_pleomorphic adenoma_20x - Chandra Krishnan.jpeg',
 '1XGn5eIgVUfKjxSdzj9Y3IoliEXNfav0o': 'ck_prostate adenocarcinoma_10x - Chandra Krishnan.jpg',
 '1gYbzHCzHyavRQvjaNL_7x8ZJOe4xPMJG': 'ck_testis seminoma_10x - Chandra Krishnan.jpg',
 '1hG0Q-JHsCS1aGnbphDShkq4bg4e2dvP-': 'ck_streak ovary_2x - Chandra Krishnan.jpg',
 '1skKiW8IPkgL4VX2vm3nIkOsC5OgAY-Te': 'ck_helicobacter gastritis_20x - Chandra Krishnan.jpg',
 '1pt7yylB_u0OsKPwp5KZLQ3-qsjsb5use': 'ck_serositis_4x - Chandra Krishnan.jpg',
 '1tbuSPy8fibAGby9LYbTonR2EcSZWojhq': 'ac_img13_400x - Amy Coffey.jpg',
 '1wHuKGW55lOOQB-3_v0apILfLM0901bP-': 'ck_parvovirus marrow_60x - Chandra Krishnan.jpg',
 '1cx3M-mWgvjonyf0p8nNCY_kiA1SpOkfn': 'Case 12_ac_200x - Amy Coffey.jpg',
 '1E8_uUE9f7JTLSwoqk7yf1h7P6gcFkdS9': 'ac_img11_200x - Amy Coffey.jpg',
 '1PQtZFlaL7ACY_7teQt3xKVGL7GL46_sV': 'ac_img10_100x - Amy Coffey.jpg',
 '1j-VlaBORBzy8MfpXRoaiZ4tCPdzucU6i': 'ck_normal marrow_10x - Chandra Krishnan.jpg',
 '1S86jJtEF6b4EURFHphLz3dR9679FZKS-': 'ck_SSA colon_10x - Chandra Krishnan.jpg',
 '1p0XE2-4pk43x0N-e70k9AolcFP76htXY': 'ck_ganglioneuroma_20x - Chandra Krishnan.jpeg',
 '1qNoyYqV-jcP0E9jN-PRGl-93CRjE4qDq': 'ck_inflamed thyroid_10x - Chandra Krishnan.jpg',
 '1QFh80UY174eEI_Un6sU_yiVMGwqt0BH7': 'ck_papillary thyroid_10x - Chandra Krishnan.jpg',
 '1-HqbvmgYf-C9x20WJonXaqY-DDafLxL4': 'ck_hyperplastic polyp_10x - Chandra Krishnan.jpg',
 '141Oc04rGlG3mn2agHl1vfSwNhoSw1XUr': 'ac_img9_400x - Amy Coffey.jpg',
 '1kRMMJeESoULeDT_H7abRicYYHy8CQ84x': 'ac_img 8_20x - Amy Coffey.jpg',
 '1JphHd1YIKoiyMVt4JOyKawMAUHc17OBN': 'ck_osteosarcoma_10x - Chandra Krishnan.jpeg',
 '1upr7TfeIIY3-tVbQA861twiZ12bxPzrB': 'ck_tubular adenoma_20x - Chandra Krishnan.jpg',
 '1JhNTnlxGaM2gb2xMgq6ztSrr2HLazgvt': 'ck_abscess actinomyces_20x - Chandra Krishnan.jpg',
 '1-Y9mT4gV0fRJH1zblGSmsTXZiddZxI9E': 'ck_PTGC_5x - Chandra Krishnan.jpeg',
 '1ugoA2iuY2QAOxwauW8eSiIATj6sx0HuQ': 'ck_PTGC_2x - Chandra Krishnan.jpeg',
 '1roBzP3oAFyXwq-WWHhDPSyzskZu1PHnx': 'ac_case7img2_200x - Amy Coffey.jpg',
 '1NIPZRXo49UYKttg3707vnuP-OR2UoFEg': 'ac_case7img1_40x - Amy Coffey.jpg',
 '1qbrr0lk93I1kOY1Zj5CXniV7SmaFOjHP': 'ac_img5_100x - Amy Coffey.jpg',
 '1fyjQ8Rr1BlM1QNU5JIeZ1nfB9s4Y-Q19': 'ac_img3_100x - Amy Coffey.jpg',
 '1bATJwjf2VzdV26LIjL4XxdX077ehmZCe': 'ac_img2_200x - Amy Coffey.jpg',
 '1275UFlHvwON4wQhKfszl12_nsded3F8j': 'Case 4.200x - Amy Coffey.jpg',
 '1UXbl3t5QE8iqpZmmK58nQ6aA-sL-620U': 'ac_img4_40x - Amy Coffey.jpg',
 '1hqoHNzs-P5BVmWOBrtwR7JdEbNGWD9Y9': 'ac_img1_400x - Amy Coffey.jpg',
 '1HzcNPcNpoi6UE7tEQ-Jtp67VUtlymr9H': 'ac_img1_100x - Amy Coffey.jpg',
 '1ijBm9hHUVi3V8BkTzqahhZJknCNwcpZZ': 'ck_plexiform schwannoma_200x - Chandra Krishnan.jpg',
 '16jp9EK7ij0p9Fij_DCcOtZy_OA8Y5ugD': 'ck_plexiform schwannoma_100x - Chandra Krishnan.jpg',
 '10UTpsgnNWSpMMuV8Duo4KhZ_4j5YhgvK': 'ck_plexiform schwannoma_20x - Chandra Krishnan.jpg',
 '1NLiQkLKSbTvxJN8E7CpjlTPQfmFtiiPS': 'ck_AIG_400x - Chandra Krishnan.jpg',
 '1iIe8REeLZMucjp7ruovp4nNLjjyx0Vi6': 'ck_AIG_200x - Chandra Krishnan.jpg',
 '1ju-llhgx5bPWXfbkVgICyYhOqnixsjjs': 'ck_AIG_100x - Chandra Krishnan.jpg',
 '1lekcubSvEOKPDgfBHyulDDPuoX_jb5Cm': 'ck_steatohepatitis_400x - Chandra Krishnan.jpg',
 '1ZCSIHMRr-oNX7wY9cLE_xyKip9iH6VOC': 'ck_steatohepatitis_200x - Chandra Krishnan.jpg',
 '1I3hak5VnuLFLAPjNB7ydLR042pKOafw6': 'ck_steatohepatitis_100x - Chandra Krishnan.jpg',
 '1btAjgoKktd7dW6rh-Lxp8Rnqmh_ir47t': 'ck_colon carcinoma_200x - Chandra Krishnan.jpg',
 '1WavtKmBC8EpjnJ3rZOZ4lvlbT9w4eQQu': 'ck_colon carcinoma_100x - Chandra Krishnan.jpg',
 '1VsI-VBMbAoZG2YnkQsL7ZQblvf-fdvkN': 'ck_colon carcinoma_20x - Chandra Krishnan.jpg',
 '1wyEZUuc-UTe9psLyMDeedRtuUxe3SVit': 'ck_acute appy_400x - Chandra Krishnan.jpg',
 '1tdRxc9qJmDM7LhbqPV38p9GH6VmsC1GU': 'ck_acute appy_100x - Chandra Krishnan.jpg',
 '1QosSQsgAHBQqxdrwXGLsT0de0sVd2BB_': 'ck_acute appy_20x - Chandra Krishnan.jpg',
 '1vEqVLVOQo85lZDaDG6cO1vwIx-N78n8F': 'ck_ameloblastoma_100x - Chandra Krishnan.jpg',
 '1Y0pBSfNeCZ8GFCXoZROSeW5w8PDZNlj0': 'ck_amerloblastoma_20x_ - Chandra Krishnan.jpg',
 '1eGnhdKunaxZCm7r5r5MHz2FH3_t43S_s': 'ck_branchial arch_200x - Chandra Krishnan.jpg',
 '14rsOnN9AySFKPQxDQ-i5MrQmytswvPRe': 'ck_branchial arch_40x - Chandra Krishnan.jpg',
 '1GQHppS17EQxogC1nTB-eu7DLzr9PlSQM': 'ck_branchial arch_20x - Chandra Krishnan.jpg',
 '1BW4uJGlQx_0rXA0QSOiKtfZ45x8_cUu0': 'wart_200x - Chandra Krishnan.jpg',
 '1KDuoZjxg4KTlozN5fcMMKxFSaxV6que6': 'wart_40x - Chandra Krishnan.jpg',
 '1l5dsr6VVkG4PBvWw0wu2mhwXdse9bh48': 'Duodenum granuloma_200x - Chandra Krishnan.jpg',
 '1VNr78I5w671gkrIyHs7AC75yrjb1lU6_': 'Duodenum granuloma_100x - Chandra Krishnan.jpg',
 '1jUe0z6wlZ0s9PZUgVj1yCL7UZav23jwz': 'Duodenum granuloma_40x - Chandra Krishnan.jpg',
 '1DKNZJQJ17SkXUrrO7jHMiKD8J6ittzus': 'MCL_400x - Chandra Krishnan.jpg',
 '1igYpj4RL0XKxq0u5qlnv6ZvqJfFjGO4u': 'MCL_200x - Chandra Krishnan.jpg',
 '1tgv50Q9W4Bm_Mk7my6Ag8mD0JWkQkYvx': 'MCL_20x - Chandra Krishnan.jpg'}

#### Assigning the Image IDs and Image Names to all the Five images as per the case

In [11]:
def assign_image_id_name(image_path):
    case_id = image_path.iloc[0]

    # Get the image path for the first image
    image1_path = image_path.iloc[1]
    image1_id = None
    image1_name = None
    if pd.notnull(image1_path):
        image1_id  = 'img_pathopen_' + str(case_id) + '_01'
        image1_drive_link = image1_path.split('=')[-1]
        image1_name = imageid_name_dict.get(image1_drive_link)

    # Get the image path for the second image
    image2_path = image_path.iloc[2]
    image2_id = None
    image2_name = None
    if pd.notnull(image2_path):
        image2_id  = 'img_pathopen_' + str(case_id) + '_02'
        image2_drive_link = image2_path.split('=')[-1]
        image2_name = imageid_name_dict.get(image2_drive_link)

    # Get the image path for the third image
    image3_path = image_path.iloc[3]
    image3_id = None
    image3_name = None
    if pd.notnull(image3_path):
        image3_id  = 'img_pathopen_' + str(case_id) + '_03'
        image3_drive_link = image3_path.split('=')[-1]
        image3_name = imageid_name_dict.get(image3_drive_link)

    # Get the image path for the fourth image
    image4_path = image_path.iloc[4]
    image4_id = None
    image4_name = None
    if pd.notnull(image4_path):
        image4_id  = 'img_pathopen_' + str(case_id) + '_04'
        image4_drive_link = image4_path.split('=')[-1]
        image4_name = imageid_name_dict.get(image4_drive_link)

    # Get the image path for the fifth image
    image5_path = image_path.iloc[5]
    image5_id = None
    image5_name = None
    if pd.notnull(image5_path):
        image5_id  = 'img_pathopen_' + str(case_id) + '_05'
        image5_drive_link = image5_path.split('=')[-1]
        image5_name = imageid_name_dict.get(image5_drive_link)
    
    return image1_id, image2_id, image3_id, image4_id, image5_id, image1_name, image2_name, image3_name, image4_name, image5_name

In [12]:
vqa_data[['Image1_ID', 'Image2_ID', 'Image3_ID', 'Image4_ID', 'Image5_ID', 'Image1_Name', 'Image2_Name', 'Image3_Name', 'Image4_Name', 'Image5_Name']] = vqa_data[['Case_ID','Image1_Path', 'Image2_Path', 'Image3_Path', 'Image4_Path', 'Image5_Path']].apply(assign_image_id_name, axis=1, result_type='expand')
vqa_data.head(10)

,Case_ID,Timestamp,Pathologist ID,Image1_Path,Organ,Categorization,Regional Anatomy,Open Ended - Question 1,Open Ended - Answer 1,Open Ended - Answer 2,...,Image1_ID,Image2_ID,Image3_ID,Image4_ID,Image5_ID,Image1_Name,Image2_Name,Image3_Name,Image4_Name,Image5_Name
0,1,2/25/2025 13:41:20,CK,https://drive.google.com/open?id=1tgv50Q9W4Bm_...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the primary architectural pattern obse...,Nodular pattern,Germinal centers are absent,...,img_pathopen_1_01,None,None,None,None,MCL_20x - Chandra Krishnan.jpg,None,None,None,None
1,2,2/25/2025 13:46:25,CK,https://drive.google.com/open?id=1igYpj4RL0XKx...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the predominant cell type seen here?,The main cell type observed here is a lymphocy...,These would best be characterized as small lym...,...,img_pathopen_2_01,None,None,None,None,MCL_200x - Chandra Krishnan.jpg,None,None,None,None
2,3,2/25/2025 13:51:37,CK,https://drive.google.com/open?id=1DKNZJQJ17SkX...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,"In this mantle cell lymphoma, what is the best...",The nuclei of the abnormal lymphocytes are mos...,This should be considered a highly cellular ti...,...,img_pathopen_3_01,None,None,None,None,MCL_400x - Chandra Krishnan.jpg,None,None,None,None
3,4,2/26/2025 11:30:23,CK,https://drive.google.com/open?id=1jUe0z6wlZ0s9...,Gastrointestinal - Small Intenstine,Infection (Benign),Intestinal villous mucosa,"In a child with poor weight gain, what are the...",Features that argue against celiac disease in ...,Granulomas here are often the consequence of u...,...,img_pathopen_4_01,None,None,None,None,Duodenum granuloma_40x - Chandra Krishnan.jpg,None,None,None,None
4,5,2/26/2025 11:42:26,CK,https://drive.google.com/open?id=1VNr78I5w671g...,Gastrointestinal - Dudenum,Infection (Benign),Intestinal villous mucosa,What are the main histologic features of a non...,Non-necrotizing granulomas are characterized b...,None,...,img_pathopen_5_01,None,None,None,None,Duodenum granuloma_100x - Chandra Krishnan.jpg,None,None,None,None
5,6,2/26/2025 11:46:09,CK,https://drive.google.com/open?id=1l5dsr6VVkG4P...,Gastrointestinal - Dudenum,Normal,Duodenum,"In villous tissue, what is the expected mixtur...",In the lamina propria of normal villous tissue...,None,...,img_pathopen_6_01,None,None,None,None,Duodenum granuloma_200x - Chandra Krishnan.jpg,None,None,None,None
6,7,2/27/2025 15:22:33,CK,https://drive.google.com/open?id=1KDuoZjxg4KTl...,Skin,Infection (Benign),Squamous epithelium,What does the presence of increased compact la...,Excess anucleate keratin on the skin surface i...,"Those refractile structures are hair shafts, w...",...,img_pathopen_7_01,None,None,None,None,wart_40x - Chandra Krishnan.jpg,None,None,None,None
7,8,2/27/2025 15:29:29,CK,https://drive.google.com/open?id=1BW4uJGlQx_0r...,Skin,Infection (Benign),Squamous epithelium,How does increased intracellular fluid manifes...,Spongiosis is the alteration of squamous epith...,Basal keratinocytes are epithelioid in shape w...,...,img_pathopen_8_01,None,None,None,None,wart_200x - Chandra Krishnan.jpg,None,None,None,None
8,9,3/6/2025 10:56:20,CK,https://drive.google.com/open?id=1GQHppS17EQxo...,Head/Neck - congenital,Congenital abnormality,Subcutaneous tissues,What is the likely clinical scenario that this...,The findings here would represent a branchial ...,The typical origin for this histology is from ...,...,img_pathopen_9_01,None,None,None,None,ck_branchial arch_20x - Chandra Krishnan.jpg,None,None,None,None
9,10,3/10/2025 9:57:15,CK,https://drive.google.com/open?id=14rsOnN9AySFK...,Pediatric - congenital,Hamartoma,Hyaline cartilage,The image shows a mixture of epithelial and me...,These are features typical of a branchial arch...,The green coloration represents the applicatio...,...,img_pathopen_10_01,None,None,None,None,ck_branchial arch_40x - Chandra Krishnan.jpg,None,None,None,None

Validating our operations

In [13]:
assert len(vqa_data[vqa_data['Image1_Path'].notnull() & vqa_data['Image1_ID'].notnull() & vqa_data['Image1_Name'].notnull()]) == 157
assert len(vqa_data[vqa_data['Image2_Path'].notnull() & vqa_data['Image2_ID'].notnull() & vqa_data['Image2_Name'].notnull()]) == 37
assert len(vqa_data[vqa_data['Image2_Path'].notnull() & vqa_data['Image2_ID'].notnull() & vqa_data['Image2_Name'].notnull()]) == 37

### Preparing the dataset in Json Format

Specifying the directories of original images and augmented images

In [14]:
original_dataset_dir = "../PathOPEN_Images"
augmented_dataset_dir = "../PathOPEN_Images_Augmented"

Putting all the values in a dictionary

In [15]:
pathopen_data_list = []

for index, row in vqa_data.iterrows():
    pathopen_dict = {}
    # Getting Case ID
    pathopen_dict["Case ID"] = int(row['Case_ID']) if pd.notnull(row['Case_ID']) else ''
    # Getting Organ
    pathopen_dict["Organ"] = row['Organ'] if pd.notnull(row['Organ']) else ''
    # Getting Categorization
    pathopen_dict["Categorization"] = row['Categorization'] if pd.notnull(row['Categorization']) else ''
    # Getting Regional Anatomy
    pathopen_dict["Regional Anatomy"] = row['Regional Anatomy']  if pd.notnull(row['Regional Anatomy']) else ''
    # Getting Open-Ended Question/Answer
    open_ended_quest1 = dict(
        {
            "Question" : row['Open Ended - Question 1'] if pd.notnull(row['Open Ended - Question 1']) else '',
            "Correct Answer" : row['Open Ended - Answer 1'] if pd.notnull(row['Open Ended - Answer 1']) else '',
            "Wrong Answer" : row['Open Ended - Wrong Answer 1'] if pd.notnull(row['Open Ended - Wrong Answer 1']) else '',
        })
    open_ended_quest2 = dict(
        {
            "Question" : row['Open Ended - Question 2'] if pd.notnull(row['Open Ended - Question 2']) else '',
            "Correct Answer" : row['Open Ended - Answer 2'] if pd.notnull(row['Open Ended - Answer 2']) else '',
            "Wrong Answer" : row['Open Ended - Wrong Answer 2'] if pd.notnull(row['Open Ended - Wrong Answer 2']) else '',
        })

    pathopen_dict["Open Ended"] = [open_ended_quest1, open_ended_quest2]

    # Getting MCQ
    pathopen_dict["MCQ"] = dict({
                                    "Question": row['MCQ - Question'] if pd.notnull(row['MCQ - Question']) else '',
                                    "Option 1": row['MCQ - Option 1'] if pd.notnull(row['MCQ - Option 1']) else '',            
                                    "Option 2": row['MCQ - Option 2'] if pd.notnull(row['MCQ - Option 2']) else '',            
                                    "Option 3": row['MCQ - Option 3'] if pd.notnull(row['MCQ - Option 3']) else '',            
                                    "Option 4": row['MCQ - Option 4'] if pd.notnull(row['MCQ - Option 4']) else '',            
                                    "Option 5": row['MCQ - Option 5'] if pd.notnull(row['MCQ - Option 5']) else '',
                                    "Answer": row['MCQ - Answer'] if pd.notnull(row['MCQ - Answer']) else ''
                                })

    # Getting Close-Ended
    pathopen_dict["Close Ended"] = dict({
                                            "Question": row['Close-Ended Question 1'] if pd.notnull(row['Close-Ended Question 1']) else '',
                                            "Answer": row['Close-Ended Answer 1'] if pd.notnull(row['Close-Ended Answer 1']) else ''
                                        })

    # Getting Images
    pathopen_images = []
    for i in range (1,6):
        image_id = row[f'Image{i}_ID']
        image_dir = ''
        image_mag = ''
        image_original_name = ''
        image_augmented_names = []

        if pd.notnull(image_id):
            image_out_path = os.path.join(output_data_images_path, image_id)
            image_name = row[f'Image{i}_Name']
            if pd.notnull(image_name):
                image_original_path = os.path.join(original_dataset_dir, image_name)
                image_augmented_dir_path = os.path.join(augmented_dataset_dir, f'{image_id}_augmented')
                if os.path.exists(image_original_path) and os.path.exists(image_augmented_dir_path):
                    # Create a directory to put the original and augmented images
                    os.makedirs(image_out_path, exist_ok=True)
                    image_dir = image_out_path
                    image_mag = row[f'Image{i}_Mag']
                    # Copy the original file with the changed name
                    image_original_name = f'{image_id}_orig.{image_name.split(".")[-1]}'
                    shutil.copy(image_original_path, os.path.join(image_out_path, image_original_name))
                    # Copy the augmented files into this folder
                    for file_name in os.listdir(image_augmented_dir_path):
                        src_file_path = os.path.join(image_augmented_dir_path, file_name)
                        dst_file_path = os.path.join(image_out_path, file_name)
                        image_augmented_names.append(file_name)
                        shutil.copy(src_file_path, dst_file_path)
        
            images_dict = dict({
                "Directory": image_dir,
                "Magnification": image_mag,
                "Original": image_original_name,
                "Augmented": image_augmented_names
            })
        
            pathopen_images.append(images_dict)

    pathopen_dict["Images"] = pathopen_images
    
    pathopen_data_list.append(pathopen_dict)

Saving the data in a json file

In [16]:
# Writing data to data.json
with open(os.path.join(output_data_path, "pathopen_data.json"), "w") as file:
    json.dump(pathopen_data_list, file, indent=4)