### Data Preparation for evaluation of PathOpen Dataset

This code will prepare the data for the evaluation of PathOpen dataset. The names of the files in the folder contain the diagnosis. So, before even anything can be done, these names need to be changed and then updated names need to be mapped back to the original data. Following is the process which will be followed for this:

1. Download the original responses file (csv), and put under the data folder. Rename some columns to acceptable names. We only have the Google Drive links in that document
2. Create the Case ID and ImageID of all the images in three folders (Image1, Image2, Image3) since we have multiple images in three different folders for a single case
3. Now prepare the questions as per the sheet for the evaluators with multiple images for each case containing all the questions

In [1]:
import pandas as pd
import numpy as np
import os
import random

In [2]:
random_state = 42
np.random.seed(random_state)
random.seed(random_state)

#### 1. Reading the data and renaming the columns to appropriate names. Also creating the Case ID

In [3]:
vqa_data = pd.read_csv('data/path_open_vqa.csv')
vqa_data = vqa_data.rename(columns={vqa_data.columns[2]: 'Image1_Path',
                                    vqa_data.columns[26]: 'Image2_Path',
                                    vqa_data.columns[27]: 'Image3_Path',
                                    vqa_data.columns[28]: 'Image4_Path',
                                    vqa_data.columns[29]: 'Image5_Path',
                                    'Image 1 Magnification ': 'Image1_Mag',
                                    'Image 2 Magnification ': 'Image2_Mag',
                                    'Image 3 Magnification ': 'Image3_Mag',
                                    'Image 4 Magnification ': 'Image4_Mag',
                                    'Image 5 Magnification ': 'Image5_Mag'})

vqa_data = vqa_data.reset_index()
vqa_data['index'] = vqa_data['index'] + 1
vqa_data = vqa_data.rename(columns={'index': 'Case_ID'})
vqa_data.head()

,Case_ID,Timestamp,Pathologist ID,Image1_Path,Organ,Categorization,Regional Anatomy,Open Ended - Question 1,Open Ended - Answer 1,Open Ended - Answer 2,...,Open Ended - Wrong Answer 1,Open Ended - Wrong Answer 2,Image2_Mag,Image3_Mag,Image4_Mag,Image5_Mag,Image2_Path,Image3_Path,Image4_Path,Image5_Path
0,1,2/25/2025 13:41:20,CK,https://drive.google.com/open?id=1tgv50Q9W4Bm_...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the primary architectural pattern obse...,Nodular pattern,Germinal centers are absent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2/25/2025 13:46:25,CK,https://drive.google.com/open?id=1igYpj4RL0XKx...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the predominant cell type seen here?,The main cell type observed here is a lymphocy...,These would best be characterized as small lym...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2/25/2025 13:51:37,CK,https://drive.google.com/open?id=1DKNZJQJ17SkX...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,"In this mantle cell lymphoma, what is the best...",The nuclei of the abnormal lymphocytes are mos...,This should be considered a highly cellular ti...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2/26/2025 11:30:23,CK,https://drive.google.com/open?id=1jUe0z6wlZ0s9...,Gastrointestinal - Small Intenstine,Infection (Benign),Intestinal villous mucosa,"In a child with poor weight gain, what are the...",Features that argue against celiac disease in ...,Granulomas here are often the consequence of u...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2/26/2025 11:42:26,CK,https://drive.google.com/open?id=1VNr78I5w671g...,Gastrointestinal - Dudenum,Infection (Benign),Intestinal villous mucosa,What are the main histologic features of a non...,Non-necrotizing granulomas are characterized b...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 2. Now creating the image_ids of multiple images within a case

In [4]:
vqa_data_upd = pd.DataFrame()
for index, row in vqa_data.iterrows():
    # Get the first image
    image_path = row['Image1_Path']
    if pd.notnull(image_path):
        row['Image_Path'] = image_path
        row['Image_ID'] = 'img_pathopen_' + str(row['Case_ID']) + '_01'
        vqa_data_upd = pd.concat([vqa_data_upd, row.to_frame().T], ignore_index=True)
    
    # Get the second image
    image_path = row['Image2_Path']
    if pd.notnull(image_path):
        row['Image_Path'] = image_path
        row['Image_ID'] = 'img_pathopen_' + str(row['Case_ID']) + '_02'
        vqa_data_upd = pd.concat([vqa_data_upd, row.to_frame().T], ignore_index=True)
    
    # Get the third image
    image_path = row['Image3_Path']
    if pd.notnull(image_path):
        row['Image_Path'] = image_path
        row['Image_ID'] = 'img_pathopen_' + str(row['Case_ID']) + '_03'
        vqa_data_upd = pd.concat([vqa_data_upd, row.to_frame().T], ignore_index=True)

vqa_data_upd.head()

,Case_ID,Timestamp,Pathologist ID,Image1_Path,Organ,Categorization,Regional Anatomy,Open Ended - Question 1,Open Ended - Answer 1,Open Ended - Answer 2,...,Image2_Mag,Image3_Mag,Image4_Mag,Image5_Mag,Image2_Path,Image3_Path,Image4_Path,Image5_Path,Image_Path,Image_ID
0,1,2/25/2025 13:41:20,CK,https://drive.google.com/open?id=1tgv50Q9W4Bm_...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the primary architectural pattern obse...,Nodular pattern,Germinal centers are absent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1tgv50Q9W4Bm_...,img_pathopen_1_01
1,2,2/25/2025 13:46:25,CK,https://drive.google.com/open?id=1igYpj4RL0XKx...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the predominant cell type seen here?,The main cell type observed here is a lymphocy...,These would best be characterized as small lym...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1igYpj4RL0XKx...,img_pathopen_2_01
2,3,2/25/2025 13:51:37,CK,https://drive.google.com/open?id=1DKNZJQJ17SkX...,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,"In this mantle cell lymphoma, what is the best...",The nuclei of the abnormal lymphocytes are mos...,This should be considered a highly cellular ti...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1DKNZJQJ17SkX...,img_pathopen_3_01
3,4,2/26/2025 11:30:23,CK,https://drive.google.com/open?id=1jUe0z6wlZ0s9...,Gastrointestinal - Small Intenstine,Infection (Benign),Intestinal villous mucosa,"In a child with poor weight gain, what are the...",Features that argue against celiac disease in ...,Granulomas here are often the consequence of u...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1jUe0z6wlZ0s9...,img_pathopen_4_01
4,5,2/26/2025 11:42:26,CK,https://drive.google.com/open?id=1VNr78I5w671g...,Gastrointestinal - Dudenum,Infection (Benign),Intestinal villous mucosa,What are the main histologic features of a non...,Non-necrotizing granulomas are characterized b...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1VNr78I5w671g...,img_pathopen_5_01

Removing the un-necessary columns

In [5]:
vqa_data_upd = vqa_data_upd.drop(columns=['Image1_Path', 'Image2_Path', 'Image3_Path'])
vqa_data_upd.head()

,Case_ID,Timestamp,Pathologist ID,Organ,Categorization,Regional Anatomy,Open Ended - Question 1,Open Ended - Answer 1,Open Ended - Answer 2,Open Ended - Question 2,...,Open Ended - Wrong Answer 1,Open Ended - Wrong Answer 2,Image2_Mag,Image3_Mag,Image4_Mag,Image5_Mag,Image4_Path,Image5_Path,Image_Path,Image_ID
0,1,2/25/2025 13:41:20,CK,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the primary architectural pattern obse...,Nodular pattern,Germinal centers are absent,What is a common component of lymph node archi...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1tgv50Q9W4Bm_...,img_pathopen_1_01
1,2,2/25/2025 13:46:25,CK,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the predominant cell type seen here?,The main cell type observed here is a lymphocy...,These would best be characterized as small lym...,What is the best description for the cell size...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1igYpj4RL0XKx...,img_pathopen_2_01
2,3,2/25/2025 13:51:37,CK,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,"In this mantle cell lymphoma, what is the best...",The nuclei of the abnormal lymphocytes are mos...,This should be considered a highly cellular ti...,What is the best description for the density a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1DKNZJQJ17SkX...,img_pathopen_3_01
3,4,2/26/2025 11:30:23,CK,Gastrointestinal - Small Intenstine,Infection (Benign),Intestinal villous mucosa,"In a child with poor weight gain, what are the...",Features that argue against celiac disease in ...,Granulomas here are often the consequence of u...,What does the granuloma in the lamina propria ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1jUe0z6wlZ0s9...,img_pathopen_4_01
4,5,2/26/2025 11:42:26,CK,Gastrointestinal - Dudenum,Infection (Benign),Intestinal villous mucosa,What are the main histologic features of a non...,Non-necrotizing granulomas are characterized b...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1VNr78I5w671g...,img_pathopen_5_01

### Generating the Google Sheet Containing the mapping between Google Drive Links and Image Names

This will help to map the image names downloaded from collected data with the Google Drive Links we have in our data

In [6]:
# function listFilesInNestedFolders(parentFolderId) {
#   // Get the initial parent folder
#   var parentfolder_id = '1VdFeRx06PrTTCbeMVQ0wQ8ML8QF8sSxM-QWlTcMx7TKQAjpWRuW5-EWJi-DtuBDPeXTbGYNm'
#   const parentFolder = DriveApp.getFolderById(parentfolder_id);
#   var folderlisting = 'File Names and Links - '+ parentfolder_id;

#   var ss = SpreadsheetApp.create(folderlisting);
#   var sheet = ss.getActiveSheet();
#   sheet.appendRow(['name','link']);

#   // Get subfolders in the current folder and process them recursively
#   var subfolders = parentFolder.getFolders();
#   while (subfolders.hasNext()) {
#     var subfolder = subfolders.next();
#     // Get files in the current folder
#     var contents = subfolder.getFiles();
#     var file;
#     var name;
#     var link;
#     while (contents.hasNext()) {
#       file = contents.next();
#       name = file.getName();
#       link = file.getUrl();
#       sheet.appendRow([name,link]);
#     }
#   }
# }

Now Download the file generated which contains mapping between google drive links and names.

In [7]:
data_dir = "data_eval"
file_name = "file_names_and_links_PathOpen_Images.csv"
file_path = os.path.join(data_dir, file_name)
google_drive_name_links = pd.read_csv(file_path)
google_drive_name_links.head()

,name,link
0,ck_HSP_5x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/1SYbssi84BMfkC...
1,ck_BALL_4x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/1XrSu7uRm3s-al...
2,ck_pschwannoma_20x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/1dGZ8MAgdKvT5w...
3,ck_CMV gastritis_4x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/11UMXpBZjiQdo0...
4,ck_rhabdo_5x - Chandra Krishnan.jpeg,https://drive.google.com/file/d/174myggtY1Fj5A...

Extracting the ID's from image links

In [8]:
vqa_data_upd['google_drive_image_id'] = vqa_data_upd['Image_Path'].apply(lambda x: x.split('=')[-1])
google_drive_name_links['google_drive_image_id'] = google_drive_name_links['link'].apply(lambda x: x.split('/')[-1])

Combining the names of the image files

In [9]:
vqa_data_upd = pd.merge(vqa_data_upd, google_drive_name_links[['google_drive_image_id', 'name']], on='google_drive_image_id', how='left')
vqa_data_upd.head()

,Case_ID,Timestamp,Pathologist ID,Organ,Categorization,Regional Anatomy,Open Ended - Question 1,Open Ended - Answer 1,Open Ended - Answer 2,Open Ended - Question 2,...,Image2_Mag,Image3_Mag,Image4_Mag,Image5_Mag,Image4_Path,Image5_Path,Image_Path,Image_ID,google_drive_image_id,name
0,1,2/25/2025 13:41:20,CK,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the primary architectural pattern obse...,Nodular pattern,Germinal centers are absent,What is a common component of lymph node archi...,...,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1tgv50Q9W4Bm_...,img_pathopen_1_01,1tgv50Q9W4Bm_Mk7my6Ag8mD0JWkQkYvx,MCL_20x - Chandra Krishnan.jpg
1,2,2/25/2025 13:46:25,CK,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,What is the predominant cell type seen here?,The main cell type observed here is a lymphocy...,These would best be characterized as small lym...,What is the best description for the cell size...,...,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1igYpj4RL0XKx...,img_pathopen_2_01,1igYpj4RL0XKxq0u5qlnv6ZvqJfFjGO4u,MCL_200x - Chandra Krishnan.jpg
2,3,2/25/2025 13:51:37,CK,Hematolymphoid - Lymph Nodes,Neoplasia (Malignant),Lymph node,"In this mantle cell lymphoma, what is the best...",The nuclei of the abnormal lymphocytes are mos...,This should be considered a highly cellular ti...,What is the best description for the density a...,...,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1DKNZJQJ17SkX...,img_pathopen_3_01,1DKNZJQJ17SkXUrrO7jHMiKD8J6ittzus,MCL_400x - Chandra Krishnan.jpg
3,4,2/26/2025 11:30:23,CK,Gastrointestinal - Small Intenstine,Infection (Benign),Intestinal villous mucosa,"In a child with poor weight gain, what are the...",Features that argue against celiac disease in ...,Granulomas here are often the consequence of u...,What does the granuloma in the lamina propria ...,...,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1jUe0z6wlZ0s9...,img_pathopen_4_01,1jUe0z6wlZ0s9PZUgVj1yCL7UZav23jwz,Duodenum granuloma_40x - Chandra Krishnan.jpg
4,5,2/26/2025 11:42:26,CK,Gastrointestinal - Dudenum,Infection (Benign),Intestinal villous mucosa,What are the main histologic features of a non...,Non-necrotizing granulomas are characterized b...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://drive.google.com/open?id=1VNr78I5w671g...,img_pathopen_5_01,1VNr78I5w671gkrIyHs7AC75yrjb1lU6_,Duodenum granuloma_100x - Chandra Krishnan.jpg

Creating a dictionary between Image_ID and name

In [10]:
name_imageid_dict = dict(zip(vqa_data_upd['name'], vqa_data_upd['Image_ID']))

In [11]:
name_imageid_dict

{'MCL_20x - Chandra Krishnan.jpg': 'img_pathopen_1_01',
 'MCL_200x - Chandra Krishnan.jpg': 'img_pathopen_2_01',
 'MCL_400x - Chandra Krishnan.jpg': 'img_pathopen_3_01',
 'Duodenum granuloma_40x - Chandra Krishnan.jpg': 'img_pathopen_4_01',
 'Duodenum granuloma_100x - Chandra Krishnan.jpg': 'img_pathopen_5_01',
 'Duodenum granuloma_200x - Chandra Krishnan.jpg': 'img_pathopen_6_01',
 'wart_40x - Chandra Krishnan.jpg': 'img_pathopen_7_01',
 'wart_200x - Chandra Krishnan.jpg': 'img_pathopen_8_01',
 'ck_branchial arch_20x - Chandra Krishnan.jpg': 'img_pathopen_121_03',
 'ck_branchial arch_40x - Chandra Krishnan.jpg': 'img_pathopen_10_01',
 'ck_branchial arch_200x - Chandra Krishnan.jpg': 'img_pathopen_11_01',
 'ck_amerloblastoma_20x_ - Chandra Krishnan.jpg': 'img_pathopen_12_01',
 'ck_ameloblastoma_100x - Chandra Krishnan.jpg': 'img_pathopen_13_01',
 'ck_acute appy_20x - Chandra Krishnan.jpg': 'img_pathopen_14_01',
 'ck_acute appy_100x - Chandra Krishnan.jpg': 'img_pathopen_15_01',
 'ck_acute appy_400x - Chandra Krishnan.jpg': 'img_pathopen_16_01',
 'ck_colon carcinoma_20x - Chandra Krishnan.jpg': 'img_pathopen_17_01',
 'ck_colon carcinoma_100x - Chandra Krishnan.jpg': 'img_pathopen_18_01',
 'ck_colon carcinoma_200x - Chandra Krishnan.jpg': 'img_pathopen_19_01',
 'ck_steatohepatitis_100x - Chandra Krishnan.jpg': 'img_pathopen_20_01',
 'ck_steatohepatitis_200x - Chandra Krishnan.jpg': 'img_pathopen_21_01',
 'ck_steatohepatitis_400x - Chandra Krishnan.jpg': 'img_pathopen_22_01',
 'ck_AIG_100x - Chandra Krishnan.jpg': 'img_pathopen_23_01',
 'ck_AIG_200x - Chandra Krishnan.jpg': 'img_pathopen_24_01',
 'ck_AIG_400x - Chandra Krishnan.jpg': 'img_pathopen_25_01',
 'ck_plexiform schwannoma_20x - Chandra Krishnan.jpg': 'img_pathopen_26_01',
 'ck_plexiform schwannoma_100x - Chandra Krishnan.jpg': 'img_pathopen_27_01',
 'ck_plexiform schwannoma_200x - Chandra Krishnan.jpg': 'img_pathopen_28_01',
 'ac_img1_100x - Amy Coffey.jpg': 'img_pathopen_29_01',
 'ac_img1_400x - Amy Coffey.jpg': 'img_pathopen_30_01',
 'ac_img4_40x - Amy Coffey.jpg': 'img_pathopen_31_01',
 'Case 4.200x - Amy Coffey.jpg': 'img_pathopen_32_01',
 'ac_img2_200x - Amy Coffey.jpg': 'img_pathopen_33_01',
 'ac_img3_100x - Amy Coffey.jpg': 'img_pathopen_34_01',
 'ac_img5_100x - Amy Coffey.jpg': 'img_pathopen_35_01',
 'ac_case7img1_40x - Amy Coffey.jpg': 'img_pathopen_36_01',
 'ac_case7img2_200x - Amy Coffey.jpg': 'img_pathopen_37_01',
 'ck_PTGC_2x - Chandra Krishnan.jpeg': 'img_pathopen_38_01',
 'ck_PTGC_5x - Chandra Krishnan.jpeg': 'img_pathopen_39_01',
 'ck_abscess actinomyces_20x - Chandra Krishnan.jpg': 'img_pathopen_40_01',
 'ck_tubular adenoma_20x - Chandra Krishnan.jpg': 'img_pathopen_41_01',
 'ck_osteosarcoma_10x - Chandra Krishnan.jpeg': 'img_pathopen_42_01',
 'ac_img 8_20x - Amy Coffey.jpg': 'img_pathopen_43_01',
 'ac_img9_400x - Amy Coffey.jpg': 'img_pathopen_44_01',
 'ck_hyperplastic polyp_10x - Chandra Krishnan.jpg': 'img_pathopen_45_01',
 'ck_papillary thyroid_10x - Chandra Krishnan.jpg': 'img_pathopen_46_01',
 'ck_inflamed thyroid_10x - Chandra Krishnan.jpg': 'img_pathopen_47_01',
 'ck_ganglioneuroma_20x - Chandra Krishnan.jpeg': 'img_pathopen_48_01',
 'ck_SSA colon_10x - Chandra Krishnan.jpg': 'img_pathopen_49_01',
 'ck_normal marrow_10x - Chandra Krishnan.jpg': 'img_pathopen_50_01',
 'ac_img10_100x - Amy Coffey.jpg': 'img_pathopen_51_01',
 'ac_img11_200x - Amy Coffey.jpg': 'img_pathopen_52_01',
 'Case 12_ac_200x - Amy Coffey.jpg': 'img_pathopen_53_01',
 'ck_parvovirus marrow_60x - Chandra Krishnan.jpg': 'img_pathopen_54_01',
 'ac_img13_400x - Amy Coffey.jpg': 'img_pathopen_55_01',
 'ck_serositis_4x - Chandra Krishnan.jpg': 'img_pathopen_56_01',
 'ck_helicobacter gastritis_20x - Chandra Krishnan.jpg': 'img_pathopen_57_01',
 'ck_streak ovary_2x - Chandra Krishnan.jpg': 'img_pathopen_58_01',
 'ck_testis seminoma_10x - Chandra Krishnan.jpg': 'img_pathopen_59_01',
 'ck_prostate adenocarcinoma_10x - Chandra Krishnan.jpg': 'img_pathopen_60_01',
 'ck_pleomorphic adenoma_20x - Chandra Krishnan.jpeg': 'img_pathopen_61_01',
 'ck_invasive melanoma_20x - Chandra Krishnan.jpeg': 'img_pathopen_62_01',
 'ck_eosinophilic esophagitis_40x - Chandra Krishnan.jpg': 'img_pathopen_63_01',
 'ac_img15_200x - Amy Coffey.jpg': 'img_pathopen_64_01',
 'ac_img16_200x - Amy Coffey.jpeg': 'img_pathopen_65_01',
 'ac_img17_20x - Amy Coffey.jpeg': 'img_pathopen_66_01',
 'ac_img18_100x - Amy Coffey.jpeg': 'img_pathopen_67_01',
 'ac_img19_200x - Amy Coffey.jpeg': 'img_pathopen_68_01',
 'ac_img20_200x - Amy Coffey.jpeg': 'img_pathopen_69_01',
 'ac_img21_200x - Amy Coffey.jpeg': 'img_pathopen_70_01',
 'ck_aneurysmal bone cyst_10x - Chandra Krishnan.jpg': 'img_pathopen_71_01',
 'ac_img22_100x - Amy Coffey.jpeg': 'img_pathopen_72_01',
 'ac_img23_100x - Amy Coffey.jpeg': 'img_pathopen_73_01',
 'ac_img24_100x - Amy Coffey.jpeg': 'img_pathopen_74_01',
 'ac_img25_200x - Amy Coffey.jpeg': 'img_pathopen_75_01',
 'ac_img26_100x - Amy Coffey.jpeg': 'img_pathopen_76_01',
 'ac_img27_200x - Amy Coffey.jpeg': 'img_pathopen_77_01',
 'ac_img28_100x - Amy Coffey.jpg': 'img_pathopen_78_01',
 'ck_dermatofibroma_4x - Chandra Krishnan.jpg': 'img_pathopen_82_01',
 'ck_placenta membrane_20x - Chandra Krishnan.jpeg': 'img_pathopen_80_01',
 'ck_torsion_10x - Chandra Krishnan.jpg': 'img_pathopen_81_01',
 'ac_img29_100x - Amy Coffey.jpeg': 'img_pathopen_83_01',
 'ac_img30_200x - Amy Coffey.jpeg': 'img_pathopen_84_01',
 'ac_img31_100x - Amy Coffey.jpeg': 'img_pathopen_85_01',
 'ac_img32_200x - Amy Coffey.jpeg': 'img_pathopen_86_01',
 'ac_img33_100x - Amy Coffey.jpeg': 'img_pathopen_87_01',
 'ac_img34_100x - Amy Coffey.jpeg': 'img_pathopen_88_01',
 'ac_img35_100x - Amy Coffey.jpeg': 'img_pathopen_89_01',
 'ac_img36_100x - Amy Coffey.jpg': 'img_pathopen_90_01',
 'ac_img37_200x - Amy Coffey.jpg': 'img_pathopen_91_01',
 'ac_img38_100x - Amy Coffey.jpg': 'img_pathopen_92_01',
 'ac_img39_100x - Amy Coffey.jpg': 'img_pathopen_93_01',
 'ac_img40_100x - Amy Coffey.jpg': 'img_pathopen_94_01',
 'ac_img25_400x - Amy Coffey.jpg': 'img_pathopen_95_01',
 'ac_img42_20x - Amy Coffey.jpeg': 'img_pathopen_96_01',
 'ck_placental infarct_5x - Chandra Krishnan.jpeg': 'img_pathopen_97_01',
 'ac_img43_200x - Amy Coffey.jpeg': 'img_pathopen_98_01',
 'ac_img44_200x - Amy Coffey.jpeg': 'img_pathopen_99_01',
 'ac_img45_100x - Amy Coffey.jpeg': 'img_pathopen_100_01',
 'ac_img46_100x - Amy Coffey.jpeg': 'img_pathopen_101_01',
 'ac_img47_200x - Amy Coffey.jpeg': 'img_pathopen_102_01',
 'ac_img48_40x - Amy Coffey.jpeg': 'img_pathopen_103_01',
 'ac_img49_100x - Amy Coffey.jpeg': 'img_pathopen_104_01',
 'ck_acute osteomyelitis_20x - Chandra Krishnan.jpg': 'img_pathopen_105_01',
 'ck_osteochondroma_4x - Chandra Krishnan.jpg': 'img_pathopen_106_01',
 'ck_thrombus fibrin_20x - Chandra Krishnan.jpg': 'img_pathopen_107_01',
 'ac_img50_100x - Amy Coffey.jpeg': 'img_pathopen_108_01',
 'ac_img51_40x - Amy Coffey.jpeg': 'img_pathopen_109_01',
 'ck_parathyroid adenoma_4x - Chandra Krishnan.jpeg': 'img_pathopen_110_01',
 'ck_ganglion cyst_20x - Chandra Krishnan.jpeg': 'img_pathopen_111_01',
 'ck_melanoma ulcer_20x - Chandra Krishnan.jpeg': 'img_pathopen_112_01',
 'ck_plasmacytoma_amyloid_20x - Chandra Krishnan.jpg': 'img_pathopen_113_01',
 'ck_osteoblastoma_20x - Chandra Krishnan.jpg': 'img_pathopen_114_01',
 'ck_marrow aplasia_4x - Chandra Krishnan.jpg': 'img_pathopen_115_01',
 'ck_marrow AML_20x - Chandra Krishnan.jpg': 'img_pathopen_116_01',
 'ck_wilms tumor_20x - Chandra Krishnan.jpeg': 'img_pathopen_117_01',
 'ck_stomach body_40x - Chandra Krishnan.jpg': 'img_pathopen_118_01',
 'ck_herniasac_4x - Chandra Krishnan.jpg': 'img_pathopen_119_01',
 'ck_bowel lymphoma_20x - Chandra Krishnan.jpg': 'img_pathopen_120_01',
 'ck_branchial arch_2x - Chandra Krishnan.jpg': 'img_pathopen_121_01',
 'ck_branchial arch_4x - Chandra Krishnan.jpg': 'img_pathopen_121_02',
 'ck_yolk sac tumor_10x - Chandra Krishnan.jpg': 'img_pathopen_122_01',
 'ck_yolk sac tumor_20x - Chandra Krishnan.jpg': 'img_pathopen_122_02',
 'ck_yolk sac tumor_40x - Chandra Krishnan.jpg': 'img_pathopen_122_03',
 'ck_fibroadenoma_2x - Chandra Krishnan.jpeg': 'img_pathopen_123_01',
 'ck_fibroadenoma_10x - Chandra Krishnan.jpeg': 'img_pathopen_123_02',
 'ck_fibroadenoma_20x - Chandra Krishnan.jpeg': 'img_pathopen_123_03',
 'ck_invasive lobular_20x - Chandra Krishnan.jpeg': 'img_pathopen_124_01',
 'ck_invasive lobular_10x - Chandra Krishnan.jpeg': 'img_pathopen_124_02',
 'ck_invasive lobular_5x - Chandra Krishnan.jpeg': 'img_pathopen_124_03',
 'ck_clear cell carcinoma_10x - Chandra Krishnan.jpeg': 'img_pathopen_125_01',
 'ck_clear cell carcinoma_2x - Chandra Krishnan.jpeg': 'img_pathopen_125_02',
 'ck_clear cell carcinoma_20x - Chandra Krishnan.jpeg': 'img_pathopen_125_03',
 'ck_endometrioid figo1_2x - Chandra Krishnan.jpeg': 'img_pathopen_126_01',
 'ck_endometrioid figo1_4x - Chandra Krishnan.jpeg': 'img_pathopen_126_02',
 'ck_endometrioid figo1_10x - Chandra Krishnan.jpeg': 'img_pathopen_126_03',
 'ck_avm_4x - Chandra Krishnan.jpg': 'img_pathopen_127_01',
 'ck_avm_2x - Chandra Krishnan.jpg': 'img_pathopen_127_02',
 'ck_avm_10x - Chandra Krishnan.jpg': 'img_pathopen_127_03',
 'ck_keloid_20x - Chandra Krishnan.jpg': 'img_pathopen_128_01',
 'ck_keloid_40x - Chandra Krishnan.jpg': 'img_pathopen_128_02',
 'ck_keloid_5x - Chandra Krishnan.jpg': 'img_pathopen_128_03',
 'ck_cellular fibroadenoma_10x - Chandra Krishnan.jpg': 'img_pathopen_129_01',
 'ck_cellular fibroadenoma_20x - Chandra Krishnan.jpg': 'img_pathopen_129_02',
 'ck_cellular fibroadenoma_4x - Chandra Krishnan.jpg': 'img_pathopen_129_03',
 'ck_fibrous obliteration_2x - Chandra Krishnan.jpg': 'img_pathopen_130_01',
 'ck_fibrous obliteration_4x - Chandra Krishnan.jpg': 'img_pathopen_130_02',
 'ck_fibrous obliteration_10x - Chandra Krishnan.jpg': 'img_pathopen_130_03',
 'ck_trichofolliculoma_2x - Chandra Krishnan.jpg': 'img_pathopen_131_01',
 'ck_trichofolliculoma_4x - Chandra Krishnan.jpg': 'img_pathopen_131_02',
 'ck_trichofolliculoma_10x - Chandra Krishnan.jpg': 'img_pathopen_131_03',
 'ck_mycobacterial infection_4x - Chandra Krishnan.jpg': 'img_pathopen_132_01',
 'ck_mycobacterial infection_2x - Chandra Krishnan.jpg': 'img_pathopen_132_02',
 'ck_mycobacterial infection_10x - Chandra Krishnan.jpg': 'img_pathopen_132_03',
 'ck_fnh_5x - Chandra Krishnan.jpeg': 'img_pathopen_133_01',
 'ck_fnh_2x - Chandra Krishnan.jpeg': 'img_pathopen_133_02',
 'ck_fnh_20x - Chandra Krishnan.jpeg': 'img_pathopen_133_03',
 'ck_liverhepc_10x - Chandra Krishnan.jpeg': 'img_pathopen_134_01',
 'ck_liverhepc_20x - Chandra Krishnan.jpeg': 'img_pathopen_134_02',
 'ck_liverhepc_2x - Chandra Krishnan.jpeg': 'img_pathopen_134_03',
 'ck_granularct_10x - Chandra Krishnan.jpeg': 'img_pathopen_135_01',
 'ck_granularct_20x - Chandra Krishnan.jpeg': 'img_pathopen_135_02',
 'ck_granularct_4x - Chandra Krishnan.jpeg': 'img_pathopen_135_03',
 'ck_tonsil scc_10x - Chandra Krishnan.jpeg': 'img_pathopen_136_01',
 'ck_tonsil scc_4x - Chandra Krishnan.jpeg': 'img_pathopen_136_02',
 'ck_tonsil scc_40x - Chandra Krishnan.jpeg': 'img_pathopen_136_03',
 'ck_CHM_10x - Chandra Krishnan.jpeg': 'img_pathopen_137_01',
 'ck_CHM_4x - Chandra Krishnan.jpeg': 'img_pathopen_137_02',
 'ck_CHM_20x - Chandra Krishnan.jpeg': 'img_pathopen_137_03',
 'ck_pheo_4x - Chandra Krishnan.jpeg': 'img_pathopen_138_01',
 'ck_pheo_2x - Chandra Krishnan.jpeg': 'img_pathopen_138_02',
 'ck_pheo_10x - Chandra Krishnan.jpeg': 'img_pathopen_138_03',
 'ck_mucinous adeno_10x - Chandra Krishnan.jpeg': 'img_pathopen_139_01',
 'ck_mucinous adeno_4x - Chandra Krishnan.jpeg': 'img_pathopen_139_02',
 'ck_mucinous adeno_20x - Chandra Krishnan.jpeg': 'img_pathopen_139_03',
 'ck_molluscum_40x - Chandra Krishnan.jpg': 'img_pathopen_140_01',
 'ck_molluscum_20x - Chandra Krishnan.jpg': 'img_pathopen_140_02',
 'ck_molluscum_10x - Chandra Krishnan.jpg': 'img_pathopen_140_03',
 'ck_okc_4x - Chandra Krishnan.jpeg': 'img_pathopen_141_01',
 'ck_okc_2x - Chandra Krishnan.jpeg': 'img_pathopen_141_02',
 'ck_okc_20x - Chandra Krishnan.jpeg': 'img_pathopen_141_03',
 'ck_graves_10x - Chandra Krishnan.jpeg': 'img_pathopen_142_01',
 'ck_graves_4x - Chandra Krishnan.jpeg': 'img_pathopen_142_02',
 'ck_graves_20x - Chandra Krishnan.jpeg': 'img_pathopen_142_03',
 'ck_panc NET_4x - Chandra Krishnan.jpeg': 'img_pathopen_143_01',
 'ck_panc NET_20x - Chandra Krishnan.jpeg': 'img_pathopen_143_02',
 'ck_panc NET_2x - Chandra Krishnan.jpeg': 'img_pathopen_143_03',
 'ck_angiosarc_20x - Chandra Krishnan.jpeg': 'img_pathopen_144_01',
 'ck_angiosarc_10x - Chandra Krishnan.jpeg': 'img_pathopen_144_02',
 'ck_angiosarc_4x - Chandra Krishnan.jpeg': 'img_pathopen_144_03',
 'ck_met yst_10x - Chandra Krishnan.jpeg': 'img_pathopen_145_01',
 'ck_met yst_20x - Chandra Krishnan.jpeg': 'img_pathopen_145_02',
 'ck_met yst_4x - Chandra Krishnan.jpeg': 'img_pathopen_145_03',
 'ck_breast lactation_10x - Chandra Krishnan.jpeg': 'img_pathopen_146_01',
 'ck_breast lactation_20x - Chandra Krishnan.jpeg': 'img_pathopen_146_02',
 'ck_breast lactation_4x - Chandra Krishnan.jpeg': 'img_pathopen_146_03',
 'ck_midlineg_10x - Chandra Krishnan.jpeg': 'img_pathopen_147_01',
 'ck_midlineg_4x - Chandra Krishnan.jpeg': 'img_pathopen_147_02',
 'ck_midlineg_20x - Chandra Krishnan.jpeg': 'img_pathopen_147_03',
 'ck_lch_20x - Chandra Krishnan.jpeg': 'img_pathopen_148_01',
 'ck_lch_10x - Chandra Krishnan.jpeg': 'img_pathopen_148_02',
 'ck_lch_4x - Chandra Krishnan.jpeg': 'img_pathopen_148_03',
 'ck_corpus luteum_10x - Chandra Krishnan.jpg': 'img_pathopen_149_01',
 'ck_corpus luteum_20x - Chandra Krishnan.jpg': 'img_pathopen_149_02',
 'ck_corpus luteum_4x - Chandra Krishnan.jpg': 'img_pathopen_149_03',
 'ck_candida esophagitis_20x - Chandra Krishnan.jpg': 'img_pathopen_150_01',
 'ck_candida esophagitis_40x - Chandra Krishnan.jpg': 'img_pathopen_150_02',
 'ck_candida esophagitis_10x - Chandra Krishnan.jpg': 'img_pathopen_150_03',
 'ck_arpckd_4x - Chandra Krishnan.jpg': 'img_pathopen_151_01',
 'ck_arpckd_2x - Chandra Krishnan.jpg': 'img_pathopen_151_02',
 'ck_arpckd_10x - Chandra Krishnan.jpg': 'img_pathopen_151_03',
 'ck_dura chl_20x - Chandra Krishnan.jpg': 'img_pathopen_152_01',
 'ck_dura chl_40x - Chandra Krishnan.jpg': 'img_pathopen_152_02',
 'ck_dura chl_10x - Chandra Krishnan.jpg': 'img_pathopen_152_03',
 'ck_rhabdo_20x - Chandra Krishnan.jpeg': 'img_pathopen_153_01',
 'ck_rhabdo_10x - Chandra Krishnan.jpeg': 'img_pathopen_153_02',
 'ck_rhabdo_5x - Chandra Krishnan.jpeg': 'img_pathopen_153_03',
 'ck_CMV gastritis_10x - Chandra Krishnan.jpeg': 'img_pathopen_154_01',
 'ck_CMV gastritis_20x - Chandra Krishnan.jpeg': 'img_pathopen_154_02',
 'ck_CMV gastritis_4x - Chandra Krishnan.jpeg': 'img_pathopen_154_03',
 'ck_pschwannoma_10x - Chandra Krishnan.jpeg': 'img_pathopen_155_01',
 'ck_pschwannoma_4x - Chandra Krishnan.jpeg': 'img_pathopen_155_02',
 'ck_pschwannoma_20x - Chandra Krishnan.jpeg': 'img_pathopen_155_03',
 'ck_BALL_10x - Chandra Krishnan.jpeg': 'img_pathopen_156_01',
 'ck_BALL_20x - Chandra Krishnan.jpeg': 'img_pathopen_156_02',
 'ck_BALL_4x - Chandra Krishnan.jpeg': 'img_pathopen_156_03',
 'ck_HSP_20x - Chandra Krishnan.jpeg': 'img_pathopen_157_01',
 'ck_HSP_10x - Chandra Krishnan.jpeg': 'img_pathopen_157_02',
 'ck_HSP_5x - Chandra Krishnan.jpeg': 'img_pathopen_157_03'}

Creating a list between names and Image_ID to rename the files in the Google Drive Folder. This step is needed so that we deidentify the image names since names contain the diagnosis.

In [12]:
vqa_data_upd[['name', 'Image_ID']].to_csv('data_eval/pathopen_image_name_id_mapping.csv', index=False)

For each folder (Image_Path1, Image_Path2, and Image_Path3), use the following script to rename the files to image_ids. Just change the ID of google drive folder for Image_Path1, Image_Path2, and Image_Path3

In [13]:
# function renameFilesFunction() {

#   const activeSpreadSheet = SpreadsheetApp.getActiveSpreadsheet(); // Get the active sheet object
#   const dataSheet = activeSpreadSheet.getSheetByName("data");

#   // Get the initial parent folder
#   var parentfolder_id = '1Bnfu5DD19rPz-29IpubkDnm2VScMURkL'
#   const parentFolder = DriveApp.getFolderById(parentfolder_id);

#   // Get data from the sheet
#   var lastRow = dataSheet.getLastRow();
#   var oldNamesArr = [];
#   var newNamesArr = [];

#   //you will have to edit these variables
#   var columnOfOldNames = 1; //name
#   var columnOfNewNames = 2; //image_id
#   //you will have to edit these variables

#   oldNamesArr = dataSheet.getRange(2, columnOfOldNames, lastRow-1).getValues();
#   newNamesArr = dataSheet.getRange(2, columnOfNewNames, lastRow-1).getValues();

#   for(let i = 0; i < oldNamesArr.length ; i++){

#     var myFileIterator = parentFolder.getFilesByName(oldNamesArr[i]);

#     while(myFileIterator.hasNext()){
#         var currentFile = myFileIterator.next();
#         console.log(currentFile.getName())
#         currentFile.setName(newNamesArr[i]);
#     }
#   }
# }

#### Now creating the evaluation dataset for all images separately as is required in the evaluation sheet

In [14]:
vqa_data_upd.columns

Index(['Case_ID', 'Timestamp', 'Pathologist ID', 'Organ', 'Categorization',
       'Regional Anatomy', 'Open Ended - Question 1', 'Open Ended - Answer 1',
       'Open Ended - Answer 2', 'Open Ended - Question 2', 'MCQ - Question',
       'MCQ - Option 1', 'MCQ - Option 2', 'MCQ - Option 3', 'MCQ - Option 4',
       'MCQ - Option 5', 'MCQ - Answer', 'Close-Ended Question 1',
       'Close-Ended Answer 1', 'Image1_Mag', 'Open Ended - Wrong Answer 1',
       'Open Ended - Wrong Answer 2', 'Image2_Mag', 'Image3_Mag', 'Image4_Mag',
       'Image5_Mag', 'Image4_Path', 'Image5_Path', 'Image_Path', 'Image_ID',
       'google_drive_image_id', 'name'],
      dtype='object')

In [15]:
case_id = []
image_id = []
image_url = []
oe_question_1 = []
oe_correct_answer_1 = []
oe_wrong_answer_1 = []
oe_question_2 = []
oe_correct_answer_2 = []
oe_wrong_answer_2 = []
mcq_oe_question = []
mcq_oe_correct_answer = []
mcq_oe_wrong_answer_1 = []
mcq_oe_wrong_answer_2 = []
mcq_oe_wrong_answer_3 = []
mcq_oe_wrong_answer_4 = []
ce_question = []
ce_correct_answer = []

for index, row in vqa_data_upd.iterrows():
    case_id.append(row['Case_ID'])
    image_id.append(row['Image_ID'])
    image_url.append(row['Image_Path'])
    oe_question_1.append(row['Open Ended - Question 1'])
    oe_correct_answer_1.append(row['Open Ended - Answer 1'])
    oe_wrong_answer_1.append(row['Open Ended - Wrong Answer 1'])
    oe_question_2.append(row['Open Ended - Question 2'])
    oe_correct_answer_2.append(row['Open Ended - Answer 2'])
    oe_wrong_answer_2.append(row['Open Ended - Wrong Answer 2'])
    mcq_oe_question.append(row['MCQ - Question'])
    mcq_answer = row['MCQ - Answer']
    if mcq_answer.strip() == 'Option 1':
        mcq_oe_correct_answer.append(row['MCQ - Option 1'])
        mcq_oe_wrong_answer_1.append(row['MCQ - Option 2'])
        mcq_oe_wrong_answer_2.append(row['MCQ - Option 3'])
        mcq_oe_wrong_answer_3.append(row['MCQ - Option 4'])
        mcq_oe_wrong_answer_4.append(row['MCQ - Option 5'])
    elif mcq_answer.strip() == 'Option 2':
        mcq_oe_correct_answer.append(row['MCQ - Option 2'])
        mcq_oe_wrong_answer_1.append(row['MCQ - Option 1'])
        mcq_oe_wrong_answer_2.append(row['MCQ - Option 3'])
        mcq_oe_wrong_answer_3.append(row['MCQ - Option 4'])
        mcq_oe_wrong_answer_4.append(row['MCQ - Option 5'])
    elif mcq_answer.strip() == 'Option 3':
        mcq_oe_correct_answer.append(row['MCQ - Option 3'])
        mcq_oe_wrong_answer_1.append(row['MCQ - Option 1'])
        mcq_oe_wrong_answer_2.append(row['MCQ - Option 2'])
        mcq_oe_wrong_answer_3.append(row['MCQ - Option 4'])
        mcq_oe_wrong_answer_4.append(row['MCQ - Option 5'])
    elif mcq_answer.strip() == 'Option 4':
        mcq_oe_correct_answer.append(row['MCQ - Option 4'])
        mcq_oe_wrong_answer_1.append(row['MCQ - Option 1'])
        mcq_oe_wrong_answer_2.append(row['MCQ - Option 2'])
        mcq_oe_wrong_answer_3.append(row['MCQ - Option 3'])
        mcq_oe_wrong_answer_4.append(row['MCQ - Option 5'])
    elif mcq_answer.strip() == 'Option 5':
        mcq_oe_correct_answer.append(row['MCQ - Option 5'])
        mcq_oe_wrong_answer_1.append(row['MCQ - Option 1'])
        mcq_oe_wrong_answer_2.append(row['MCQ - Option 2'])
        mcq_oe_wrong_answer_3.append(row['MCQ - Option 3'])
        mcq_oe_wrong_answer_4.append(row['MCQ - Option 4'])
        
    ce_question.append(row['Close-Ended Question 1'])
    ce_correct_answer.append(row['Close-Ended Answer 1'])

In [16]:
pathopen_eval_data = pd.DataFrame({
    'Case_ID': case_id,
    'Image_ID': image_id,
    'Image_URL': image_url,
    'OE_Question_1': oe_question_1,
    'OE_Correct_Answer_1': oe_correct_answer_1,
    'OE_Wrong_Answer_1': oe_wrong_answer_1,
    'OE_Question_2': oe_question_2,
    'OE_Correct_Answer_2': oe_correct_answer_2,
    'OE_Wrong_Answer_2': oe_wrong_answer_2,
    'MCQ_OE_Question': mcq_oe_question,
    'MCQ_OE_Correct_Answer': mcq_oe_correct_answer,
    'MCQ_OE_Wrong_Answer_1': mcq_oe_wrong_answer_1,
    'MCQ_OE_Wrong_Answer_2': mcq_oe_wrong_answer_2,
    'MCQ_OE_Wrong_Answer_3': mcq_oe_wrong_answer_3,
    'MCQ_OE_Wrong_Answer_4': mcq_oe_wrong_answer_4,
    'CE_Question': ce_question,
    'CE_Correct_Answer': ce_correct_answer
})

pathopen_eval_data.head()

,Case_ID,Image_ID,Image_URL,OE_Question_1,OE_Correct_Answer_1,OE_Wrong_Answer_1,OE_Question_2,OE_Correct_Answer_2,OE_Wrong_Answer_2,MCQ_OE_Question,MCQ_OE_Correct_Answer,MCQ_OE_Wrong_Answer_1,MCQ_OE_Wrong_Answer_2,MCQ_OE_Wrong_Answer_3,MCQ_OE_Wrong_Answer_4,CE_Question,CE_Correct_Answer
0,1,img_pathopen_1_01,https://drive.google.com/open?id=1tgv50Q9W4Bm_...,What is the primary architectural pattern obse...,Nodular pattern,NaN,What is a common component of lymph node archi...,Germinal centers are absent,NaN,What is the organ represented?,Lymph Node,Adrenal gland,Pancreas,Bone marrow,Retina,Is this a normal pattern observed?,No
1,2,img_pathopen_2_01,https://drive.google.com/open?id=1igYpj4RL0XKx...,What is the predominant cell type seen here?,The main cell type observed here is a lymphocy...,NaN,What is the best description for the cell size...,These would best be characterized as small lym...,NaN,If these are CD5 B-cell lineage lymphocytes in...,Mantle cell lymphoma,Small lymphocytic lymphoma,Diffuse large B-cell lymphoma,Hairy cell leukemia,Follicular lymphoma,Is the nucleus to cytoplasmic ratio of these l...,Yes
2,3,img_pathopen_3_01,https://drive.google.com/open?id=1DKNZJQJ17SkX...,"In this mantle cell lymphoma, what is the best...",The nuclei of the abnormal lymphocytes are mos...,NaN,What is the best description for the density a...,This should be considered a highly cellular ti...,NaN,What nuclear feature suggests increased growth...,Frequent mitotic figures,Large nuclear size,Increased red blood cells,Low nuclear:cytoplasmic ratio,Many histiocytes,Does this tumor have morphologic features of d...,No
3,4,img_pathopen_4_01,https://drive.google.com/open?id=1jUe0z6wlZ0s9...,"In a child with poor weight gain, what are the...",Features that argue against celiac disease in ...,NaN,What does the granuloma in the lamina propria ...,Granulomas here are often the consequence of u...,NaN,Which of the following chronic gastrointestina...,Crohn disease,Ulcerative colitis,Giardia gastroenteritis,Celiac disease,Norovirus,Is the mucosal architecture normal?,Yes
4,5,img_pathopen_5_01,https://drive.google.com/open?id=1VNr78I5w671g...,What are the main histologic features of a non...,Non-necrotizing granulomas are characterized b...,NaN,NaN,NaN,NaN,In a pediatric age patient with this biopsy wh...,Paneth cells,Goblet cells,Brush border,Mucous cells,Histiocytes,Are duodenum granulomas typically found with c...,No

### Suffling the dataframe with fixed seed

In [17]:
pathopen_eval_data_shuffle = pathopen_eval_data.sample(frac=1, random_state=random_state).reset_index(drop=True)
pathopen_eval_data_shuffle.head()

,Case_ID,Image_ID,Image_URL,OE_Question_1,OE_Correct_Answer_1,OE_Wrong_Answer_1,OE_Question_2,OE_Correct_Answer_2,OE_Wrong_Answer_2,MCQ_OE_Question,MCQ_OE_Correct_Answer,MCQ_OE_Wrong_Answer_1,MCQ_OE_Wrong_Answer_2,MCQ_OE_Wrong_Answer_3,MCQ_OE_Wrong_Answer_4,CE_Question,CE_Correct_Answer
0,153,img_pathopen_153_03,https://drive.google.com/open?id=174myggtY1Fj5...,How would one describe the abnormal infiltrate...,"The abnormal cells appear to show round, large...",The abnormal cells appear to show spindled mor...,What is the likely diagnosis for this middle e...,"In the context of the immunohistochemistry, th...","In the context of the immunohistochemistry, th...",What is the most likely genetic alteration pre...,The histology and immunohistochemistry suggest...,The histology and immunohistochemistry suggest...,The histology and immunohistochemistry suggest...,The histology and immunohistochemistry suggest...,The histology and immunohistochemistry suggest...,Could this image that depicts a malignant sarc...,Yes
1,67,img_pathopen_67_01,https://drive.google.com/open?id=1iNpg3DgTGpNZ...,Considering this is an ovarian mass in a 16 ye...,This ovarian tumor has a mixture of somatic ti...,This ovarian tumor has a mixture of benign som...,Considering this is an ovarian mass in a 16 ye...,There is immature neuroepithelium which is the...,There is immature neuroectodermal tissue which...,Considering this is an ovarian mass in a 16 ye...,High grade immature teratoma,Ovarian small cell carcinoma,Mature cystic teratoma,PNET arising in an immature teratoma,Intermediate-to-poorly differentiated Sertoli-...,Is this tumor graded based on the amount of gl...,No
2,10,img_pathopen_10_01,https://drive.google.com/open?id=14rsOnN9AySFK...,The image shows a mixture of epithelial and me...,These are features typical of a branchial arch...,NaN,The image shows green coloration on portions o...,The green coloration represents the applicatio...,NaN,The green coloration along the edge of the tis...,Tissue marking ink,Melanin,Hemosiderin,Dystrophic calcification,Necrosis,Does the image show features of superimposed i...,No
3,137,img_pathopen_137_03,https://drive.google.com/open?id=1tWQ8FH1UEg1U...,What is the abnormality observed in this image...,The image depicts a molar pregnancy with unifo...,The image depicts an early pregnancy with dila...,What is the expected chromosomal findings pred...,The image depicts likely complete hydatidiform...,The image depicts likely complete hydatidiform...,What cell type in this image is represented by...,The multinucleated cells in question are syncy...,The multinucleated cells in question are osteo...,The multinucleated cells in question are osteo...,The multinucleated cells in question are synov...,The multinucleated cells in question are megak...,Does the image from this placenta suggest an u...,No
4,16,img_pathopen_16_01,https://drive.google.com/open?id=1wyEZUuc-UTe9...,Describe the histological findings are present...,There is a dense neutrophilic infiltrate in th...,NaN,What laboratory findings are expected to be se...,Elevated white blood cells (WBC) with or witho...,NaN,"In this image from the appendix mucosa, what i...",Neutrophils,Megakaryocytes,Macrophages,Lymphocytes,Plasma cells,Is eosinophilic infiltration a hallmark featur...,No

Dividing the dataframe into five small dfs

In [18]:
df_part_len = int(len(pathopen_eval_data_shuffle)/5)
pathopen_eval_data_shuffle_part1 = pathopen_eval_data_shuffle.iloc[0:df_part_len]
pathopen_eval_data_shuffle_part2 = pathopen_eval_data_shuffle.iloc[df_part_len:2*df_part_len]
pathopen_eval_data_shuffle_part3 = pathopen_eval_data_shuffle.iloc[2*df_part_len:3*df_part_len]
pathopen_eval_data_shuffle_part4 = pathopen_eval_data_shuffle.iloc[3*df_part_len:4*df_part_len]
pathopen_eval_data_shuffle_part5 = pathopen_eval_data_shuffle.iloc[4*df_part_len:len(pathopen_eval_data_shuffle)]

In [19]:
pathopen_eval_data_shuffle_part1.to_csv('data_eval/pathopen_vqa_part1.csv', index=False)
pathopen_eval_data_shuffle_part2.to_csv('data_eval/pathopen_vqa_part2.csv', index=False)
pathopen_eval_data_shuffle_part3.to_csv('data_eval/pathopen_vqa_part3.csv', index=False)
pathopen_eval_data_shuffle_part4.to_csv('data_eval/pathopen_vqa_part4.csv', index=False)
pathopen_eval_data_shuffle_part5.to_csv('data_eval/pathopen_vqa_part5.csv', index=False)